(function(){
// Bangla flashcards - separate JS to avoid clashes with other pages
const banglaFlashcards = [
    { fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অ আ ক খ", a: "প্রাথমিক জ্ঞান\nEnglish: Basic knowledge/fundamentals.\nExplanation: Elementary literacy or first lessons.\nExample (BN): 'শিশুদের অ আ ক খ শেখানো হয় স্কুলে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকটবিকট", a: "ছটফটানি\nEnglish: Restlessness / fidgeting.\nExplanation: A state of nervous agitation or inability to sit still.\nExample (BN): 'পরীক্ষার আগে শিক্ষার্থীরা অকটবিকটে ভুগছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকর্মার ধাড়ি", a: "একেবারে অকেজো, অত্যন্ত অলস ব্যক্তি\nEnglish: Completely useless / extremely lazy person.\nExplanation: Someone who is idle, lazy, and contributes nothing productive.\nExample (BN): 'তিনি অকর্মার ধাড়ির মতো সারাদিন বসে থাকেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকালকুষ্মাণ্ড", a: "অপদার্থ / অকেজো\nEnglish: Incompetent / worthless.\nExplanation: A person or thing that is useless or lacks any value.\nExample (BN): 'তার অকালকুষ্মাণ্ড মনোভাব সবার বিরক্তির কারণ।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকালপক্ব", a: "ডেপো, বয়সের তুলনায় বেশি পাকা\nEnglish: Prematurely mature / appearing older than one's age.\nExplanation: When something shows maturity, ripeness or development earlier than expected.\nExample (BN): 'এই বালক অকালপক্বের মতো বুদ্ধিমান।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকালসন্ধ্যা", a: "সময়ের আগেই কষ্টের শুরু\nEnglish: Untimely adversity / early onset of trouble.\nExplanation: Hardship or suffering that begins earlier than expected.\nExample (BN): 'অপ্রস্তুত অবস্থায় তার অকালসন্ধ্যা নেমে এল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকালে বাদল", a: "অপ্রত্যাশিত বাধা\nEnglish: Unexpected obstacle / untimely hindrance.\nExplanation: An unforeseen difficulty that appears at an inconvenient time.\nExample (BN): 'তার পরিকল্পনায় অকালে বাদল বাধা হয়ে দাঁড়িয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকুস্থল", a: "যে কোন ঘটনার স্থান\nEnglish: Scene / location of an incident.\nExplanation: The place where an event or occurrence takes place.\nExample (BN): 'পুলিশ অকুস্থলে পৌঁছে তদন্ত করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকূল দরিয়া/পাথর", a: "ভীষণ বিপদ\nEnglish: Grave danger / extreme peril.\nExplanation: A metaphor for being in a very dangerous or desperate situation.\nExample (BN): 'ঋণের বোঝা তাকে অকূল দরিয়ায় ফেলে দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকূলে কূল পাওয়া", a: "নিরুপায় অবস্থা থেকে উদ্ধার পাওয়া\nEnglish: To find shore / to be rescued from helplessness.\nExplanation: Finding safety or relief after being in a desperate situation.\nExample (BN): 'অনেক কষ্টের পর অবশেষে তারা অকূলে কূল পেল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকূলে পড়া", a: "বিপদে পড়া\nEnglish: To fall into danger.\nExplanation: To be caught or trapped in a difficult or dangerous situation.\nExample (BN): 'অভিভাবকের মৃত্যুতে শিশুরা অকূলে পড়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকূলে/অকূল পাথরে ভাসা", a: "বিপদে দিশেহারা হওয়া\nEnglish: To be adrift / to be at a loss in danger.\nExplanation: To become bewildered or helpless when facing danger.\nExample (BN): 'কর্মহীন হয়ে সে অকূল পাথরে ভাসছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকূলের কূল", a: "বিপদে ত্রাণকর্তা/রক্ষাকর্তা\nEnglish: Rescuer / savior in danger.\nExplanation: A person or thing that provides help or relief during hardship.\nExample (BN): 'দুর্ঘটনায় সেই ব্যক্তি ছিল অকূলের কূল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অকূলের ভেলা", a: "একান্ত নিরুপায় অবস্থার অবলম্বন\nEnglish: A desperate refuge / last resort in helplessness.\nExplanation: Being in a state of complete despair with no other option.\nExample (BN): 'অর্থাভাবে তিনি অকূলের ভেলায় আশ্রয় নিয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অক্কা পাওয়া/অক্কাপ্রাপ্তি", a: "মারা যাওয়া/মৃত্যু\nEnglish: To die / death.\nExplanation: The end of life or a euphemistic way of saying someone has died.\nExample (BN): 'তার বাবা অক্কা পেয়ে তিন বছর হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অক্ষয়বট", a: "অতিবৃদ্ধ ব্যক্তি\nEnglish: Very old person / extremely aged person.\nExplanation: An unusually ancient or elderly individual.\nExample (BN): 'গ্রামের অক্ষয়বট বৃদ্ধ অনেক গল্প বলেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অক্ষরে অক্ষরে", a: "সম্পূর্ণভাবে\nEnglish: Word for word / completely / literally.\nExplanation: Following something exactly as stated without any deviation.\nExample (BN): 'শিক্ষক যা বলেছেন তা অক্ষরে অক্ষরে মেনে চলো।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অখাদ্যে অবাদ্যে", a: "অপদার্থ / অকর্মণ্য\nEnglish: Useless / incompetent in all respects.\nExplanation: Someone who is ineffective and worthless in every way.\nExample (BN): 'সে অখাদ্যে অবাদ্যে এবং কোন কাজেই লাগে না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগতির গতি", a: "ঈশ্বর/অসহায়ের শেষ অবলম্বন\nEnglish: God / divine providence / last resort.\nExplanation: Referring to God or fate as the ultimate solution when no other option exists.\nExample (BN): 'অগতির গতি এখন শুধু আল্লাহর দরবারে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগস্ত্যযাত্রা", a: "চিরদিনের জন্য বিদায়/মৃত্যু\nEnglish: Permanent departure / eternal farewell / death.\nExplanation: A final goodbye or the end of life, referring to the sage Agastya's journey to the south.\nExample (BN): 'তার অগস্ত্যযাত্রা হয়েছে আমাদের সবার জন্য বেদনার।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগাধ জল/সমুদ্র", a: "চরম বিপদে\nEnglish: In extreme danger / in deep water.\nExplanation: Being in a very difficult or dangerous situation (like drowning in deep water).\nExample (BN): 'তার ব্যবসায়িক সমস্যায় তিনি অগাধ জলে পড়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগাধ জলের মাছ", a: "সুচতুর ব্যক্তি/চালাক ব্যক্তি\nEnglish: Cunning / shrewd / clever person.\nExplanation: Someone who is skillful and clever, like a fish navigating deep waters.\nExample (BN): 'তিনি অগাধ জলের মাছের মতো সব ফন্দি জানেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগ্নিচক্ষু", a: "কঠোর দৃষ্টি\nEnglish: Stern look / fierce gaze.\nExplanation: A harsh, angry, or piercing look that shows disapproval or anger.\nExample (BN): 'শিক্ষক অগ্নিচক্ষুতে শিক্ষার্থীর দিকে তাকালেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগ্নিপরীক্ষা", a: "কঠিন পরীক্ষা\nEnglish: Ordeal / trial by fire.\nExplanation: A severe test or challenging examination that tests one's character or ability.\nExample (BN): 'ব্যবসায়ের শুরুতে তাকে অনেক অগ্নিপরীক্ষার মুখোমুখি হতে হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগ্নিমূল্য", a: "চড়া মূল্য/বেশি দাম\nEnglish: Exorbitant price / very high cost.\nExplanation: An unusually high or inflated price for something.\nExample (BN): 'এই পণ্যের অগ্নিমূল্য রয়েছে বাজারে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগ্নিতে ঘৃতাহুতি", a: "উত্তেজনা/ক্রোধবৃদ্ধি\nEnglish: Fanning the flames / adding fuel to the fire.\nExplanation: Doing something that intensifies anger or conflict.\nExample (BN): 'তার কথা শুনে তার ক্রোধে অগ্নিতে ঘৃতাহুতি হল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগ্নিতে বারি বর্ষণ", a: "উত্তেজনা/ক্রোধ কমে যাওয়া\nEnglish: Pouring water on fire / calming down anger.\nExplanation: Cooling down rage or reducing the intensity of conflict.\nExample (BN): 'তার শান্তি প্রস্তাবে ঝগড়ায় অগ্নিতে বারি বর্ষণ হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অগ্নিশর্মা", a: "খুব রাগান্বিত\nEnglish: Very angry / enraged.\nExplanation: Being in a state of extreme anger or fury.\nExample (BN): 'তার অগ্নিশর্মা মুখ দেখে সবাই চুপ হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অঙ্কুরে বিনষ্ট", a: "শুরুতেই শেষ\nEnglish: Nipped in the bud / ruined from the start.\nExplanation: When something is destroyed or fails right from its beginning.\nExample (BN): 'দুর্নীতির কারণে প্রকল্পটি অঙ্কুরে বিনষ্ট হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অঙ্গন জল হওয়া", a: "ভয় পাওয়া\nEnglish: To be terrified / to lose courage.\nExplanation: Becoming extremely frightened, as if one's body has turned to water.\nExample (BN): 'সাপ দেখে তার শরীর অঙ্গন জল হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অঙ্গুলি হেলন", a: "আঙুল নেড়ে ইশারা/নির্দেশ\nEnglish: A gesture with the finger / beckoning.\nExplanation: Directing or signaling someone through hand or finger movement.\nExample (BN): 'তিনি অঙ্গুলি হেলনে আমাকে পাশে ডেকে নিলেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অচলায়তন", a: "যেখানে অগ্রগতি নেই\nEnglish: A place of stagnation / where progress stops.\nExplanation: A situation or place where no development or advancement is possible.\nExample (BN): 'সেই অঞ্চল অচলায়তনের মতো কোন উন্নয়ন হয়নি।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অজমূর্খ", a: "নিরেট বোকা\nEnglish: Utter fool / complete idiot.\nExplanation: Someone who is profoundly stupid or lacking intelligence.\nExample (BN): 'এমন সহজ সমস্যাও সমাধান করতে পারে না, সে অজমূর্খ।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অজগরবৃত্তি", a: "আলসেমি\nEnglish: Laziness / indolence / sloth.\nExplanation: The habit of being lazy and inactive, like a python.\nExample (BN): 'তার অজগরবৃত্তি তাকে সফলতার পথ থেকে দূরে রেখেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অজগ্রাম/অজপাড়া/অজপাড়াগ্রাম", a: "নিতান্ত ক্ষুদ্র/ অপরিচিত পল্লী\nEnglish: Remote village / unknown settlement.\nExplanation: A very small or obscure village that is barely known.\nExample (BN): 'তিনি অজপাড়াগ্রাম থেকে এসে এখন শহরে থাকেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অজাতশত্রু", a: "যার শত্রু নাই\nEnglish: One without enemies / peaceful person.\nExplanation: Someone who has no enmity with anyone and lives peacefully.\nExample (BN): 'অজাতশত্রুর মতো তার সবার সাথে সুসম্পর্ক রয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অজাতশ্মশ্রু", a: "অল্পবয়সী\nEnglish: Young / beardless / youthful.\nExplanation: Referring to someone who is still very young and not yet a full adult.\nExample (BN): 'এই অজাতশ্মশ্রু যুবক এমন গুরুত্বপূর্ণ দায়িত্ব নিতে পারবে না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অথৈ জল", a: "ভীষণ বিপদ/ বিপদে দিশেহারা\nEnglish: Deep water / extreme danger.\nExplanation: A situation of grave danger or being completely lost and helpless.\nExample (BN): 'অথৈ জলে পড়ে তারা একে অপরকে ডেকে চেঁচাচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অথৈ জলের মাছ", a: "সুচতুর ব্যক্তি/চাপা স্বভাবের লোক\nEnglish: Cunning person / secretive individual.\nExplanation: Someone who is clever and tactful, or one who keeps their thoughts hidden.\nExample (BN): 'তিনি অথৈ জলের মাছের মতো তার ভাবনা প্রকাশ করেন না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অদৃষ্টের কিল", a: "ভাগ্যের মার\nEnglish: The stroke of fate / misfortune.\nExplanation: Misery or suffering caused by bad luck or destiny.\nExample (BN): 'অদৃষ্টের কিল খেয়ে তার জীবন সর্বস্ব হারিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অদৃষ্টের পরিহাস/ফের", a: "ভাগ্যবিড়ম্বনা/ভাগ্যের নিষ্ঠুরতা\nEnglish: Cruel twist of fate / destiny's mockery.\nExplanation: When fate or chance plays a cruel or ironic trick on someone.\nExample (BN): 'অদৃষ্টের পরিহাস এমনভাবে তাকে যন্ত্রণা দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অধঃপাতে যাওয়া", a: "উচ্ছন্নে যাওয়া/ধ্বংস হওয়া\nEnglish: To be destroyed / to be ruined.\nExplanation: Complete ruin or destruction of something or someone.\nExample (BN): 'অনৈতিক কাজের কারণে তার ব্যবসা অধঃপাতে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অনধিকারচর্চা", a: "সীমার বাইরে পদক্ষেপ\nEnglish: Exceeding one's authority / overstepping boundaries.\nExplanation: Taking action beyond one's rights or jurisdiction.\nExample (BN): 'এটি অনধিকারচর্চা, তুমি এমন সিদ্ধান্ত নিতে পারো না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অনলে জল পড়া", a: "কঠিন রাগ কমে যাওয়া\nEnglish: Cooling down / anger subsiding.\nExplanation: When intense anger or rage gradually diminishes.\nExample (BN): 'তার মৃদু কথায় অনলে জল পড়ার মতো রাগ কমে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অনুরোধে ঢেঁকি গেলা", a: "অনুরোধে কাজ সম্পন্ন করতে ইচ্ছুক\nEnglish: Willing to help upon request / complying with request.\nExplanation: Being ready to do something when asked, even if difficult.\nExample (BN): 'তিনি অনুরোধে ঢেঁকি গেলার মতো সাহায্য করেছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অনেক কাঠখড় পোড়ানো", a: "বহু চেষ্টা ও পরিশ্রম করা\nEnglish: To go through great effort / to work hard.\nExplanation: Spending a lot of time, energy, and resources to accomplish something.\nExample (BN): 'এই স্বপ্ন পূরণে আমাকে অনেক কাঠখড় পোড়াতে হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্তঃসারশূন্য", a: "গুণহীন ব্যক্তি\nEnglish: Hollow / lacking inner worth.\nExplanation: Someone who appears good on the surface but lacks any real virtue or substance.\nExample (BN): 'তার অন্তঃসারশূন্য ব্যক্তিত্ব দ্রুত স্পষ্ট হয়ে উঠল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্তর টিপুনি", a: "গোপন ব্যথা\nEnglish: Hidden pain / suppressed grief.\nExplanation: Internal suffering that one keeps hidden from others.\nExample (BN): 'তার মুখে হাসি থাকলেও অন্তর টিপুনি তাকে কাঁদায়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধকার দেখা", a: "বিপদে দিশেহারা হয়ে পড়া\nEnglish: To see darkness / to become confused in danger.\nExplanation: Losing one's way or sense of direction in a difficult situation.\nExample (BN): 'বিস্ফোরণে সবাই অন্ধকার দেখে যন্ত্রণা ক্রন্দন করল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধকারে ঢিল ছোঁড়া/মারা", a: "অনুমানে/আন্দাজে কাজ করা\nEnglish: Shooting in the dark / guessing blindly.\nExplanation: Acting without proper information or taking a wild guess.\nExample (BN): 'সঠিক তথ্য ছাড়া অন্ধকারে ঢিল মারা ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধকারে থাকা", a: "কিছু না জানা/সম্পূর্ণ অজানা/থই না পাওয়া\nEnglish: To be in the dark / to be completely unaware.\nExplanation: Not knowing anything about a situation or being kept uninformed.\nExample (BN): 'এই ব্যাপারে সম্পূর্ণ অন্ধকারে থাকলাম আমরা।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধকারে হাতড়ানো", a: "অনুমান করা\nEnglish: To grope in the dark / to guess.\nExplanation: Trying to find one's way without clear knowledge or information.\nExample (BN): 'সমাধান খুঁজতে গিয়ে তিনি অন্ধকারে হাতড়াচ্ছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধের যটি/ষষ্ঠি/নড়ি", a: "অসহায়ের একমাত্র অবলম্বন\nEnglish: A blind man's staff / only support.\nExplanation: The only thing or person that a helpless person can rely upon.\nExample (BN): 'দারিদ্র্যের মধ্যে তার সন্তান অন্ধের যটির মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধের হস্তীদর্শন", a: "অসম্পূর্ণ বিচার/সিদ্ধান্ত\nEnglish: Partial judgment / incomplete understanding.\nExplanation: Making a judgment based on incomplete information, like a blind man touching parts of an elephant.\nExample (BN): 'আধেক তথ্যে আধেক বিচার হয় যা অন্ধের হস্তীদর্শন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধবিশ্বাস", a: "নির্বিচার আস্থা\nEnglish: Blind faith / unconditional belief.\nExplanation: Believing something without any critical thinking or evidence.\nExample (BN): 'অন্ধবিশ্বাস করা বিজ্ঞানের সাথে সামঞ্জস্যপূর্ণ নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্ধিসন্ধি", a: "কুমতলব/ষড়যন্ত্র\nEnglish: Conspiracy / scheming.\nExplanation: Secret plotting or machination against someone.\nExample (BN): 'তার সাফল্যে ঈর্ষান্বিত হয়ে অনেকে অন্ধিসন্ধি করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্নকষ্ট", a: "খাদ্যাভাব\nEnglish: Food scarcity / famine.\nExplanation: Lack of sufficient food or sustenance.\nExample (BN): 'অন্নকষ্টে ভুগে সেই পরিবার দান খোঁজে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্নজল", a: "জীবিকা\nEnglish: Livelihood / means of subsistence.\nExplanation: The basic necessities of life (food and water) or the way one earns for living.\nExample (BN): 'সততার সাথে অন্নজল অর্জন করাই প্রকৃত সম্পদ।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "বসে বসে খাওয়া", a: "পরিশ্রম ছাড়া ভোগ করা\nEnglish: To live without labor / to eat without working.\nExplanation: Enjoying the benefits of life without putting in any effort.\nExample (BN): 'বসে বসে খাওয়ার মানসিকতা সমাজের ক্ষতি করে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অন্নের সংস্থান", a: "জীবিকার উপায়\nEnglish: Means of livelihood / source of food.\nExplanation: The way or method by which one earns or obtains food.\nExample (BN): 'শিক্ষা পেলে অন্নের সংস্থান সহজ হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অপাঙ্গে দেখা", a: "আড়াচোখে দেখা\nEnglish: Sidelong glance / look askance.\nExplanation: Looking at someone with suspicion or disdain through the corner of one's eye.\nExample (BN): 'তার অপাঙ্গে দেখার অর্থ বুঝতে পেরে আমি বিরক্ত হয়েছি।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অপোগণ্ড", a: "অপদার্থ/কোন কাজের নয়\nEnglish: Useless / good-for-nothing.\nExplanation: Someone or something that is of no value or utility.\nExample (BN): 'এই অপোগণ্ড যন্ত্রটি ফেলে দেওয়া উচিত।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অবরে-সবরে", a: "কখনো সখনো/কালেভদ্রে\nEnglish: Now and then / occasionally / rarely.\nExplanation: Something that happens infrequently or at irregular intervals.\nExample (BN): 'তিনি অবরে-সবরে শহরে গিয়ে দেখা করেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অবস্থা বুঝে ব্যবস্থা", a: "পরিস্থিতি বিবেচনায় কার্যক্রম গ্রহণ\nEnglish: To adapt one's action to circumstance.\nExplanation: Making decisions that are appropriate and suitable to the current situation.\nExample (BN): 'বুদ্ধিমান ব্যক্তি অবস্থা বুঝে ব্যবস্থা নিয়ে থাকে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অবোধের খাটনি ভারি", a: "বোকাকে বেশি খাটানো যায়\nEnglish: The fool works hard / foolish people work the most.\nExplanation: Simple-minded people can be easily put to work and exploited.\nExample (BN): 'অবোধের খাটনি ভারি বলে তাকে সবচেয়ে বেশি কাজ দেওয়া হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অভাবে স্বভাব নষ্ট", a: "অর্থাভাবে সৎপথ থেকে বিচ্যুতি\nEnglish: Poverty corrupts character / need makes one dishonest.\nExplanation: When someone becomes dishonest or immoral due to lack of resources.\nExample (BN): 'অভাবে স্বভাব নষ্ট হয়ে তিনি চুরি করতে শুরু করেছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অমনি অমনি", a: "কারণ ছাড়া\nEnglish: Without reason / for no cause.\nExplanation: Something happening or being said without any particular reason.\nExample (BN): 'কোন কারণ ছাড়াই অমনি অমনি তিনি রেগে গেলেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অমাবস্যার চাঁদ", a: "দুর্লভ বস্তু/যার দেখা পাওয়া যায় না\nEnglish: A new moon / something extremely rare or never seen.\nExplanation: Something that is virtually impossible to find or see.\nExample (BN): 'এমন সৎ ব্যক্তি অমাবস্যার চাঁদের মতো বিরল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অমৃতে অরুচি", a: "অতি প্রিয় বিষয়ের প্রতি অনীহা\nEnglish: Indifference to the best things / disgust with nectar.\nExplanation: Losing interest in something one loves, or becoming apathetic.\nExample (BN): 'বার বার হতাশায় তার সংগীতপ্রেমে অমৃতে অরুচি দেখা দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অরণ্যে রোদন", a: "নিষ্ফল আবেদন\nEnglish: Crying in the wilderness / fruitless appeal.\nExplanation: Making an appeal or request that goes unheeded or has no effect.\nExample (BN): 'তার ন্যায়ের দাবি অরণ্যে রোদনের মতো ব্যর্থ হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অর্জুনের গাণ্ডীব", a: "দুষ্ট দমনকারী\nEnglish: Destroyer of evil / one who punishes the wicked.\nExplanation: A powerful force or person capable of eliminating wrongdoing.\nExample (BN): 'তিনি অর্জুনের গাণ্ডীবের মতো অন্যায় দূর করেছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অর্থদণ্ড/নাশ", a: "অকারণে অর্থব্যয়\nEnglish: Wasteful spending / unnecessary expense.\nExplanation: Spending money foolishly without any valid reason.\nExample (BN): 'তার এই অর্থদণ্ড দেখে পরিবার হতাশ হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অর্ধচন্দ্র দেওয়া", a: "গলাধাক্কা দেওয়া\nEnglish: To choke / to grab by the throat.\nExplanation: Strangling someone or giving them a choking grip.\nExample (BN): 'ঝগড়ায় তিনি তার প্রতিদ্বন্দ্বীকে অর্ধচন্দ্র দিয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অশনিসঙ্কেত", a: "ঘোর বিপদের সম্ভাবনা\nEnglish: Sign of impending doom / warning of danger.\nExplanation: An indication or warning that great danger is approaching.\nExample (BN): 'অশনিসঙ্কেত দেখে সমাজ প্রস্তুত হতে শুরু করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অষ্টকপালে", a: "অভাগা\nEnglish: Unfortunate / ill-fated.\nExplanation: Someone who is cursed with bad luck from birth.\nExample (BN): 'অষ্টকপালে হিসেবে তার জীবন দুর্ভোগে পূর্ণ।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অষ্টপ্রহর", a: "সারা দিনরাত\nEnglish: Day and night / all the time / constantly.\nExplanation: Throughout the entire twenty-four hours or continuously.\nExample (BN): 'অষ্টপ্রহর পরিশ্রম করে তিনি সফল হয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অসার কথা", a: "অর্থহীন/আজেবাজে কথাবার্তা\nEnglish: Nonsense / meaningless talk.\nExplanation: Speech or statements that have no substance or real meaning.\nExample (BN): 'তার অসার কথা শুনে সবাই উপেক্ষা করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অহরহ", a: "প্রতিনিয়ত\nEnglish: Constantly / continuously / day after day.\nExplanation: Something that happens repeatedly or without stopping.\nExample (BN): 'অহরহ বৃষ্টি হচ্ছে এই অঞ্চলে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অহি-নকুল সম্পর্ক", a: "ভীষণ শত্রুতা\nEnglish: Enmity like that of a snake and mongoose / bitter rivalry.\nExplanation: A relationship of extreme hostility and opposition.\nExample (BN): 'তাদের অহি-নকুল সম্পর্ক সবাই জানে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "অহিতে বিপরীত", a: "মন্দ থেকে ভালো\nEnglish: To turn harm into good / to reverse bad fortune.\nExplanation: Transforming a negative situation into a positive one.\nExample (BN): 'তার বুদ্ধিমত্তা অহিতে বিপরীত করে দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁকুপাঁকু", a: "অত্যন্ত ব্যাকুলতা/ছটফট করা\nEnglish: Extreme restlessness / agitation.\nExplanation: Being very anxious or agitated, unable to stay calm.\nExample (BN): 'পরীক্ষার আগে সে আঁকুপাঁকু করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁটকুড়ে", a: "হতভাগ্য\nEnglish: Unlucky / unfortunate.\nExplanation: Describes someone who suffers from misfortune.\nExample (BN): 'সেই পরিবারটি খুব আঁটকুড়ে; সবসময় সমস্যা পায়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁটকপালে", a: "নিঃসন্তান\nEnglish: Childless / barren.\nExplanation: Refers to couples who have no children.\nExample (BN): 'তারা দীর্ঘদিন বিবাহিত কিন্তু আঁটকপালে রয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁতে ঘা দেওয়া", a: "অন্তরে কষ্ট দেওয়া/প্রকাশ্যে অপমান করা\nEnglish: To wound someone emotionally / to publicly humiliate.\nExplanation: Causing deep emotional pain or insulting someone openly.\nExample (BN): 'তার তিক্ত মন্তব্য সবাইকে আঁতে ঘা দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁতের টান", a: "নাড়ীর/প্রাণের টান (আবেগী আকর্ষণ)\nEnglish: Emotional/innate attachment.\nExplanation: A deep, instinctive pull or longing toward someone or something.\nExample (BN): 'দেশের মাটির প্রতি আঁতের টান তাকে ফিরিয়ে এনেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁধার ঘরের প্রদীপ/আঁধার মানিক", a: "দুঃখীর ঘরে একমাত্র সুখের বস্তু/প্রাণাধিক সন্তান\nEnglish: The only light/treasure in a poor person's home.\nExplanation: Refers to a beloved child who is the sole comfort in a poor household.\nExample (BN): 'স্বামী-মায়ের জন্য সেই ছেলে আঁধার ঘরের প্রদীপ।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁধারে ঢিল ছোঁড়া", a: "আন্দাজে কিছু বলা/করা\nEnglish: To say or do something by guesswork / to speculate.\nExplanation: Acting or commenting without certainty, relying on conjecture.\nExample (BN): 'তথ্য না জেনে আঁধারে ঢিল ছোঁড়া ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঁস্তাকুড়ের পাত/পাতা", a: "হেয় ব্যক্তি\nEnglish: A contemptible / despicable person.\nExplanation: Someone considered lowly or unworthy of respect.\nExample (BN): 'বেশি মিথ্যাচার করে সে আঁস্তাকুড়ের পাত সহ অন্যান্যদের অসম্মান পায়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আউলা-ঝাউলা", a: "অপরিচ্ছন্ন/আলুথালু/এলোমেলো\nEnglish: Unkempt / messy / shabby.\nExplanation: Describes clothing or appearance that is untidy and disorderly.\nExample (BN): 'বহুদিন না গোছানোর ফলে তার পোশাক আউলা-ঝাউলা হয়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাট মূর্খ", a: "জড়বুদ্ধিসম্পন্ন/নিরেট বোকা\nEnglish: Stupid / blockheaded.\nExplanation: A person lacking common sense or quick understanding.\nExample (BN): 'এমন ভুল করবে এমন আচরণ দেখে তাকে আকাট মূর্খ বলা হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকার-ইঙ্গিতে", a: "চোখ ও মুখের ভঙ্গীতে\nEnglish: By gestures / through looks and expressions.\nExplanation: Communicating silently using facial expressions or gestures.\nExample (BN): 'তারা আলোচনা না করে আকৃতি-ইঙ্গিতে বোঝে নেয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশ থেকে পড়া", a: "না জানার ভান করা\nEnglish: To pretend ignorance / to play dumb.\nExplanation: Acting as if one does not know or understand something.\nExample (BN): 'প্রশ্ন এলে সে আকাশ থেকে পড়ার ভান করল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশ ভেঙে পড়া (মাথায়)", a: "হঠাৎ ভীষণ বিপদে দিশেহারা হওয়া\nEnglish: To be suddenly overwhelmed by disaster.\nExplanation: Experiencing sudden catastrophic trouble that leaves one helpless.\nExample (BN): 'ব্যবসায় নষ্ট হলে তার জীবন আকাশ ভেঙে পড়ার মতো হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশকুসুম", a: "অসম্ভব\nEnglish: Fantastical / impossible.\nExplanation: Something fanciful or unreal, not likely to happen.\nExample (BN): 'তার পরিকল্পনা আকাশকুসুম; বাস্তবে সম্ভব নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশচুম্বি/ছোঁয়া", a: "অতি উচ্চ\nEnglish: Sky-high / extremely lofty.\nExplanation: Reaching very great heights in achievement, price, or stature.\nExample (BN): 'তার সফলতা আকাশচুম্বি; সবাই দারুণভাবে প্রশংসা করে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশপাতাল চিন্তা/ভাবনা", a: "উদ্দেশ্যহীন নানা প্রকার দুশ্চিন্তা\nEnglish: Frivolous or aimless worries.\nExplanation: Worries and thoughts that are exaggerated or without purpose.\nExample (BN): 'বহু সময় আকাশপাতাল চিন্তায় কাটে তার, তবে কোনো ফল হয় না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশে তোলা", a: "প্রশংসায় পঞ্চমুখ\nEnglish: To praise lavishly / to exalt.\nExplanation: Showering someone or something with high praise.\nExample (BN): 'সংসদে তার কাজ আকাশে তোলা হলো।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশে থুথু ফেলা", a: "নিজের ক্ষতি করা\nEnglish: To spit at the sky / to harm oneself.\nExplanation: Acting in a way that ultimately causes self-harm or embarrassment.\nExample (BN): 'অলোচনার মধ্যে নিজের বিরুদ্ধে বাক্যবল রাখলে তা আকাশে থুথু ফেলার সমান।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকাশের চাঁদ হাতে পাওয়া", a: "দুর্লভ বস্তু প্রাপ্তি\nEnglish: To obtain the moon from the sky / to achieve something rare.\nExplanation: Acquiring something very rare or nearly impossible.\nExample (BN): 'এই পুরস্কার পেয়ে যেন আকাশের চাঁদ হাতে পেলাম।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আকুলি-বিকুলি", a: "অতিশয় ব্যাকুলতা\nEnglish: Extreme eagerness / frantic anxiety.\nExplanation: Being excessively restless or anxious about something.\nExample (BN): 'বিলাপ শুনে সবাই আকুলি-বিকুলি হয়ে উঠল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আক্কেল গুড়ুম", a: "হতবুদ্ধি/স্তম্ভিত\nEnglish: Stupefied / bewildered.\nExplanation: Being so surprised or shocked that one becomes speechless.\nExample (BN): 'অফারের খবর পেয়ে সে আক্কেল গুড়ুম হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আক্কেলদাঁত না গজানো", a: "অপরিণত বুদ্ধির পরিচয় দেওয়া\nEnglish: Showing immaturity / lack of wisdom.\nExplanation: Acting in a childish or immature way that reveals poor judgment.\nExample (BN): 'এমন সিদ্ধান্তে সে আক্কেলদাঁত না গজানোর প্রমাণ দিল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আক্কেল সেলামী", a: "নির্বুদ্ধিতার দণ্ড/ভুলের মাশুল\nEnglish: Penalty for foolishness / consequence of error.\nExplanation: The adverse result one suffers for being foolish.\nExample (BN): 'তার অবহেলার কারণে এখন আক্কেল সেলামী ভোগ করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আখের গুছানো", a: "ভবিষ্যৎ গুছিয়ে নেওয়া\nEnglish: To secure the future / to arrange provision.\nExplanation: Making plans or provisions for future stability.\nExample (BN): 'বাচ্চাদের পড়াশোনা নিয়ে আখের গুছিয়েছে তারা।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আখেরি জমানা", a: "শেষযুগ/কলিযুগ\nEnglish: The end times / final era.\nExplanation: Referring metaphorically to a distant final period or decline.\nExample (BN): 'বড়লোকের আচরণ দেখে মনে হয় আখেরি জমানা এসে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আগড়ম বাগড়ম", a: "অপ্রাসঙ্গিক/অর্থহীন কথাবার্তা\nEnglish: Irrelevant chatter / nonsense.\nExplanation: Talk that has no relevance or substance.\nExample (BN): 'তার আগড়ম বাগড়ম থামাও, কাজে লাগবে না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আগুন ধরানো/লাগানো", a: "তীব্র বিরোধ সৃষ্টি করা\nEnglish: To set fire / to incite intense conflict.\nExplanation: Provoking or initiating a serious dispute or fight.\nExample (BN): 'রাজনৈতিক উসকানিতে কেউ আগুন ধরাচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আগুন নিয়ে খেলা", a: "বিপজ্জনক বিষয় নিয়ে নাড়াচাড়া করা\nEnglish: Playing with fire / dabbling in danger.\nExplanation: Engaging in risky or dangerous behavior that may have severe consequences.\nExample (BN): 'অনভিজ্ঞ দ্বারা এই প্রকল্পে আগুন নিয়ে খেলা হচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আগুন লাগা সংসার", a: "নষ্ট হচ্ছে এমন সংসার\nEnglish: A family falling apart / household in ruin.\nExplanation: Describes a household undergoing severe trouble or breakdown.\nExample (BN): 'অর্থ নিয়ে তর্ক-আপসায় তাদের আগুন লাগা সংসার হয়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আগুনে ঘি ঢালা", a: "রাগ বাড়ানো\nEnglish: To add fuel to the fire / to increase anger.\nExplanation: Doing something that worsens an already tense situation.\nExample (BN): 'অতিরিক্ত মন্তব্য করে সে আলোচনায় আগুনে ঘি ঢালল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঙ্গুল ফুলে কলাগাছ", a: "হঠাৎ প্রচুর ধনসম্পত্তির মালিক\nEnglish: To suddenly become very wealthy.\nExplanation: Gaining sudden and unexpected wealth or fortune.\nExample (BN): 'ব্যবসায় এক সফল ডিল, আর তিনি আঙ্গুল ফুলে কলাগাছ।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আজগুবী কথা", a: "আজেবাজে/অপ্রাসঙ্গিক কথা\nEnglish: Absurd / nonsensical talk.\nExplanation: Saying strange or irrelevant things that make no sense.\nExample (BN): 'তার আজগুবী কথা সবাই বাজে মনে করে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আটপৌরে", a: "সবসময়ের পোশাক\nEnglish: Everyday wear / habitual clothing.\nExplanation: Clothing one habitually wears or always keeps.\nExample (BN): 'সে সাধারণত সাদা কুর্তা পড়েন, সেটাই তার আটপৌরে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আঠারো মাসে বছর", a: "দীর্ঘ সময়\nEnglish: A very long time / seemingly endless.\nExplanation: An idiom meaning a period that feels much longer than usual.\nExample (BN): 'প্রতীক্ষায় দিনগুলি আঠারো মাসে বছর মনে হচ্ছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আড়িপাতা", a: "আড়াল থেকে লুকিয়ে কথা শোনা\nEnglish: Eavesdropping / spying.\nExplanation: Observing or listening secretly to others' conversations.\nExample (BN): 'সে দরজার আড়িপাতা দিয়ে কথোপকথন শুনছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আদা জল খেয়ে পড়ে থাকা", a: "কার্যসিদ্ধির জন্য ধর্ণা দেওয়া\nEnglish: To stage a sit-in / to fast or protest for success.\nExplanation: Taking a persistent stand (often physically) to achieve a purpose.\nExample (BN): 'তারা অনুমতির জন্য আদা জল খেয়ে পড়ে আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আদা জল খেয়ে লাগা", a: "প্রাণপণ চেষ্টা করা\nEnglish: To strive desperately / to make a last-ditch effort.\nExplanation: Putting in extreme effort to accomplish something.\nExample (BN): 'প্রকল্প শেষ করতে তারা আদা জল খেয়ে লাগল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আদায় কাঁচকলায়", a: "তিক্ত সম্পর্ক/চিরশত্রুতা\nEnglish: Bitter enmity / perpetual hostility.\nExplanation: Longstanding and unforgiving hostility between parties.\nExample (BN): 'দুই পরিবারের মধ্যে আদায় কাঁচকলায় চলে এসেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আদার ব্যাপারী", a: "নগণ্য/সামান্য ব্যক্তি\nEnglish: A petty person / insignificant trader.\nExplanation: Someone of little importance or influence.\nExample (BN): 'সব ব্যাপারে হিংসুক-সামান্য মানুষকে আদার ব্যাপারী বলা হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আদ্যোপান্ত", a: "শুরু থেকে শেষ\nEnglish: From beginning to end / thoroughly.\nExplanation: Covering something completely from start to finish.\nExample (BN): 'আদ্যোপান্ত প্রতিবেদনটি পড়ে টেবিলে বসেছি।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আপন কোলে ঝোল টানা", a: "নিজের স্বার্থ দেখা\nEnglish: To mind one's own interest / look after one's own benefit.\nExplanation: Acting primarily to serve one's personal advantage.\nExample (BN): 'তিনি সবসময় আপন কোলে ঝোল টানেন, অন্যদের চিন্তা করেন না।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আপন পায়ে কুড়াল মারা", a: "নিজের ক্ষতি করা\nEnglish: To bring harm upon oneself / to shoot oneself in the foot.\nExplanation: Doing something that results in one's own detriment.\nExample (BN): 'অজ্ঞানে কার্যকলে সে আপন পায়ে কুড়াল মারল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আমড়া কাঠের ঢেঁকি", a: "অপদার্থ\nEnglish: Worthless / incompetent.\nExplanation: Someone inept or not fit for useful work.\nExample (BN): 'কাজে তার আমড়া কাঠের ঢেঁকি স্বভাব আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আমতা আমতা করা", a: "অস্পষ্ট স্বীকারোক্তি\nEnglish: Vague confession / hesitant admission.\nExplanation: Making an unclear or half-hearted admission or statement.\nExample (BN): 'সে অপরাধ সম্পর্কে আমতা আমতা করে স্বীকার করল।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আলাদীনের প্রদীপ", a: "অবিশ্বাস্য ঘটনা ঘটানোর কারিগর\nEnglish: Aladdin's lamp / a source of miraculous help.\nExplanation: Metaphor for something that produces incredible, almost magical results.\nExample (BN): 'নতুন আবিষ্কারটি আলাদীনের প্রদীপের মতো সহায়ক হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আলালের ঘরের দুলাল", a: "অতি আদরে বড়লোকের নষ্টপুত্র\nEnglish: Spoiled son of a wealthy patron.\nExplanation: A child excessively pampered by a rich family, often becoming arrogant.\nExample (BN): 'শহরে সে আলালের ঘরের দুলাল হিসেবে পরিচিত।'" }
    ,{ fullSection: "SECTION: Bangla - Sayings", topic: "Sayings", q: "আষাঢ়ে গল্প", a: "আজগুবি/কাল্পনিক কাহিনী\nEnglish: Tall tale / fanciful story.\nExplanation: A story that is fanciful, implausible, or made up.\nExample (BN): 'তার আষাঢ়ে গল্পগুলো শুনে সবাই হেসে ফেলে।'" }
];


let currentIndex = 0;
let filtered = banglaFlashcards;

function $(id){return document.getElementById(id)}

function display(i){
    if (!filtered || filtered.length===0) return;
    if (i<0) i=0; if (i>=filtered.length) i=filtered.length-1;
    currentIndex=i;
    const c = filtered[i];
    $('sectionText').textContent = c.fullSection;
    $('questionText').textContent = c.q;
    $('answerText').innerText = c.a;
    $('cardCount').textContent = `${i+1} / ${filtered.length}`;
    $('flashcard').classList.remove('flipped');
    const p = ((i+1)/filtered.length)*100; $('progressFill').style.width = p+'%';
}

function next(){ if (currentIndex<filtered.length-1) display(currentIndex+1); }
function prev(){ if (currentIndex>0) display(currentIndex-1); }

function toggle(){ $('flashcard').classList.toggle('flipped'); }

function openModal(){ $('topicModal').style.display='block'; }
function closeModal(){ $('topicModal').style.display='none'; }

function populateTopics(){
    const topics = Array.from(new Set(filtered.map(c=>c.topic)));
    const list = $('topicList'); list.innerHTML='';
    topics.forEach(t=>{
        const div = document.createElement('div'); div.className='topic-item'; div.textContent = `${t} (${filtered.filter(c=>c.topic===t).length} cards)`;
        div.onclick = ()=>{ filtered = banglaFlashcards.filter(c=>c.topic===t); display(0); document.querySelectorAll('.topic-item').forEach(e=>e.classList.remove('active')); div.classList.add('active'); closeModal(); };
        list.appendChild(div);
    });
}

document.addEventListener('DOMContentLoaded', ()=>{
    populateTopics();
    display(0);
    $('flashcard').addEventListener('click', toggle);
    $('nextBtn').addEventListener('click', next);
    $('prevBtn').addEventListener('click', prev);
    $('sectionHeader').addEventListener('click', openModal);
    document.querySelector('.close').addEventListener('click', closeModal);
    document.getElementById('topicModal').addEventListener('click', function(e){ if (e.target===this) closeModal(); });
    document.addEventListener('keydown', function(e){ if (e.key==='ArrowRight') next(); if (e.key==='ArrowLeft') prev(); if (e.key===' ') { e.preventDefault(); toggle(); } });
});

})();
