(function(){
// Bangla flashcards - separate JS to avoid clashes with other pages
const banglaFlashcards = [
    { fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অ আ ক খ", a: "প্রাথমিক জ্ঞান\nEnglish: Basic knowledge/fundamentals.\nExplanation: Elementary literacy or first lessons.\nExample (BN): 'শিশুদের অ আ ক খ শেখানো হয় স্কুলে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকটবিকট", a: "ছটফটানি\nEnglish: Restlessness / fidgeting.\nExplanation: A state of nervous agitation or inability to sit still.\nExample (BN): 'পরীক্ষার আগে শিক্ষার্থীরা অকটবিকটে ভুগছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকর্মার ধাড়ি", a: "একেবারে অকেজো, অত্যন্ত অলস ব্যক্তি\nEnglish: Completely useless / extremely lazy person.\nExplanation: Someone who is idle, lazy, and contributes nothing productive.\nExample (BN): 'তিনি অকর্মার ধাড়ির মতো সারাদিন বসে থাকেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকালকুষ্মাণ্ড", a: "অপদার্থ / অকেজো\nEnglish: Incompetent / worthless.\nExplanation: A person or thing that is useless or lacks any value.\nExample (BN): 'তার অকালকুষ্মাণ্ড মনোভাব সবার বিরক্তির কারণ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকালপক্ব", a: "ডেপো, বয়সের তুলনায় বেশি পাকা\nEnglish: Prematurely mature / appearing older than one's age.\nExplanation: When something shows maturity, ripeness or development earlier than expected.\nExample (BN): 'এই বালক অকালপক্বের মতো বুদ্ধিমান।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকালসন্ধ্যা", a: "সময়ের আগেই কষ্টের শুরু\nEnglish: Untimely adversity / early onset of trouble.\nExplanation: Hardship or suffering that begins earlier than expected.\nExample (BN): 'অপ্রস্তুত अবস्थाय় तार अकालसन्ध्या नेमे एल।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকালে বাদল", a:"অপ্রত্যাশিত বাধা\nEnglish : Unexpected obstacle / untimely hindrance.\nExplanation : An unforeseen difficulty that appears at an inconvenient time.\nExample (BN) : 'तार परिकल्पनाय अकाले बादल बाधा होये दाँड़िये छे।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকুস্থল", a: "যে কোন ঘটনার স্থান\nEnglish: Scene / location of an incident.\nExplanation: The place where an event or occurrence takes place.\nExample (BN): 'পুলিশ অকুস্থলে পৌঁছে তদন্ত করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকূল দরিয়া/পাথর", a: "ভীষণ বিপদ\nEnglish: Grave danger / extreme peril.\nExplanation: A metaphor for being in a very dangerous or desperate situation.\nExample (BN): 'ঋণের বোঝা তাকে অকূল দরিয়ায় ফেলে দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকূলে কূল পাওয়া", a: "নিরুপায় অবস্থা থেকে উদ্ধার পাওয়া\nEnglish: To find shore / to be rescued from helplessness.\nExplanation: Finding safety or relief after being in a desperate situation.\nExample (BN): 'অনেক কষ্টের পর অবশেষে তারা অকূলে কূল পেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকূলে পড়া", a: "বিপদে পড়া\nEnglish: To fall into danger.\nExplanation: To be caught or trapped in a difficult or dangerous situation.\nExample (BN): 'অভিভাবকের মৃত্যুতে শিশুরা অকূলে পড়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকূলে/অকূল পাথরে ভাসা", a: "বিপদে দিশেহারা হওয়া\nEnglish: To be adrift / to be at a loss in danger.\nExplanation: To become bewildered or helpless when facing danger.\nExample (BN): 'কর্মহীন হয়ে সে অকূল পাথরে ভাসছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকূলের কূল", a: "বিপদে ত্রাণকর্তা/রক্ষাকর্তা\nEnglish: Rescuer / savior in danger.\nExplanation: A person or thing that provides help or relief during hardship.\nExample (BN): 'দুর্ঘটনায় সেই ব্যক্তি ছিল অকূলের কূল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অকূলের ভেলা", a: "একান্ত নিরুপায় অবস্থার অবলম্বন\nEnglish: A desperate refuge / last resort in helplessness.\nExplanation: Being in a state of complete despair with no other option.\nExample (BN): 'অর্থাভাবে তিনি অকূলের ভেলায় আশ্রয় নিয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অক্কা পাওয়া/অক্কাপ্রাপ্তি", a: "মারা যাওয়া/মৃত্যু\nEnglish: To die / death.\nExplanation: The end of life or a euphemistic way of saying someone has died.\nExample (BN): 'তার বাবা অক্কা পেয়ে তিন বছর হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অক্ষয়বট", a: "অতিবৃদ্ধ ব্যক্তি\nEnglish: Very old person / extremely aged person.\nExplanation: An unusually ancient or elderly individual.\nExample (BN): 'গ্রামের অক্ষয়বট বৃদ্ধ অনেক গল্প বলেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অক্ষরে অক্ষরে", a: "সম্পূর্ণভাবে\nEnglish: Word for word / completely / literally.\nExplanation: Following something exactly as stated without any deviation.\nExample (BN): 'শিক্ষক যা বলেছেন তা অক্ষরে অক্ষরে মেনে চলো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অখাদ্যে অবাদ্যে", a: "অপদার্থ / অকর্মণ্য\nEnglish: Useless / incompetent in all respects.\nExplanation: Someone who is ineffective and worthless in every way.\nExample (BN): 'সে অখাদ্যে অবাদ্যে এবং কোন কাজেই লাগে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগতির গতি", a: "ঈশ্বর/অসহায়ের শেষ অবলম্বন\nEnglish: God / divine providence / last resort.\nExplanation: Referring to God or fate as the ultimate solution when no other option exists.\nExample (BN): 'অগতির গতি এখন শুধু আল্লাহর দরবারে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগস্ত্যযাত্রা", a: "চিরদিনের জন্য বিদায়/মৃত্যু\nEnglish: Permanent departure / eternal farewell / death.\nExplanation: A final goodbye or the end of life, referring to the sage Agastya's journey to the south.\nExample (BN): 'তার অগস্ত্যযাত্রা হয়েছে আমাদের সবার জন্য বেদনার।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগাধ জল/সমুদ্র", a: "চরম বিপদে\nEnglish: In extreme danger / in deep water.\nExplanation: Being in a very difficult or dangerous situation (like drowning in deep water).\nExample (BN): 'তার ব্যবসায়িক সমস্যায় তিনি অগাধ জলে পড়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগাধ জলের মাছ", a: "সুচতুর ব্যক্তি/চালাক ব্যক্তি\nEnglish: Cunning / shrewd / clever person.\nExplanation: Someone who is skillful and clever, like a fish navigating deep waters.\nExample (BN): 'তিনি অগাধ জলের মাছের মতো সব ফন্দি জানেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগ্নিচক্ষু", a: "কঠোর দৃষ্টি\nEnglish: Stern look / fierce gaze.\nExplanation: A harsh, angry, or piercing look that shows disapproval or anger.\nExample (BN): 'শিক্ষক অগ্নিচক্ষুতে শিক্ষার্থীর দিকে তাকালেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগ্নিপরীক্ষা", a: "কঠিন পরীক্ষা\nEnglish: Ordeal / trial by fire.\nExplanation: A severe test or challenging examination that tests one's character or ability.\nExample (BN): 'ব্যবসায়ের শুরুতে তাকে অনেক অগ্নিপরীক্ষার মুখোমুখি হতে হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগ্নিমূল্য", a: "চড়া মূল্য/বেশি দাম\nEnglish: Exorbitant price / very high cost.\nExplanation: An unusually high or inflated price for something.\nExample (BN): 'এই পণ্যের অগ্নিমূল্য রয়েছে বাজারে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগ্নিতে ঘৃতাহুতি", a: "উত্তেজনা/ক্রোধবৃদ্ধি\nEnglish: Fanning the flames / adding fuel to the fire.\nExplanation: Doing something that intensifies anger or conflict.\nExample (BN): 'তার কথা শুনে তার ক্রোধে অগ্নিতে ঘৃতাহুতি হল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগ্নিতে বারি বর্ষণ", a: "উত্তেজনা/ক্রোধ কমে যাওয়া\nEnglish: Pouring water on fire / calming down anger.\nExplanation: Cooling down rage or reducing the intensity of conflict.\nExample (BN): 'তার শান্তি প্রস্তাবে ঝগড়ায় অগ্নিতে বারি বর্ষণ হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অগ্নিশর্মা", a: "খুব রাগান্বিত\nEnglish: Very angry / enraged.\nExplanation: Being in a state of extreme anger or fury.\nExample (BN): 'তার অগ্নিশর্মা মুখ দেখে সবাই চুপ হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অঙ্কুরে বিনষ্ট", a: "শুরুতেই শেষ\nEnglish: Nipped in the bud / ruined from the start.\nExplanation: When something is destroyed or fails right from its beginning.\nExample (BN): 'দুর্নীতির কারণে প্রকল্পটি অঙ্কুরে বিনষ্ট হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অঙ্গন জল হওয়া", a: "ভয় পাওয়া\nEnglish: To be terrified / to lose courage.\nExplanation: Becoming extremely frightened, as if one's body has turned to water.\nExample (BN): 'সাপ দেখে তার শরীর অঙ্গন জল হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অঙ্গুলি হেলন", a: "আঙুল নেড়ে ইশারা/নির্দেশ\nEnglish: A gesture with the finger / beckoning.\nExplanation: Directing or signaling someone through hand or finger movement.\nExample (BN): 'তিনি অঙ্গুলি হেলনে আমাকে পাশে ডেকে নিলেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অচলায়তন", a: "যেখানে অগ্রগতি নেই\nEnglish: A place of stagnation / where progress stops.\nExplanation: A situation or place where no development or advancement is possible.\nExample (BN): 'সেই অঞ্চল অচলায়তনের মতো কোন উন্নয়ন হয়নি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অজমূর্খ", a: "নিরেট বোকা\nEnglish: Utter fool / complete idiot.\nExplanation: Someone who is profoundly stupid or lacking intelligence.\nExample (BN): 'এমন সহজ সমস্যাও সমাধান করতে পারে না, সে অজমূর্খ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অজগরবৃত্তি", a: "আলসেমি\nEnglish: Laziness / indolence / sloth.\nExplanation: The habit of being lazy and inactive, like a python.\nExample (BN): 'তার অজগরবৃত্তি তাকে সফলতার পথ থেকে দূরে রেখেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অজগ্রাম/অজপাড়া/অজপাড়াগ্রাম", a: "নিতান্ত ক্ষুদ্র/ অপরিচিত পল্লী\nEnglish: Remote village / unknown settlement.\nExplanation: A very small or obscure village that is barely known.\nExample (BN): 'তিনি অজপাড়াগ্রাম থেকে এসে এখন শহরে থাকেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অজাতশত্রু", a: "যার শত্রু নাই\nEnglish: One without enemies / peaceful person.\nExplanation: Someone who has no enmity with anyone and lives peacefully.\nExample (BN): 'অজাতশত্রুর মতো তার সবার সাথে সুসম্পর্ক রয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অজাতশ্মশ্রু", a: "অল্পবয়সী\nEnglish: Young / beardless / youthful.\nExplanation: Referring to someone who is still very young and not yet a full adult.\nExample (BN): 'এই অজাতশ্মশ্রু যুবক এমন গুরুত্বপূর্ণ দায়িত্ব নিতে পারবে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অথৈ জল", a: "ভীষণ বিপদ/ বিপদে দিশেহারা\nEnglish: Deep water / extreme danger.\nExplanation: A situation of grave danger or being completely lost and helpless.\nExample (BN): 'অথৈ জলে পড়ে তারা একে অপরকে ডেকে চেঁচাচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অথৈ জলের মাছ", a: "সুচতুর ব্যক্তি/চাপা স্বভাবের লোক\nEnglish: Cunning person / secretive individual.\nExplanation: Someone who is clever and tactful, or one who keeps their thoughts hidden.\nExample (BN): 'তিনি অথৈ জলের মাছের মতো তার ভাবনা প্রকাশ করেন না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অদৃষ্টের কিল", a: "ভাগ্যের মার\nEnglish: The stroke of fate / misfortune.\nExplanation: Misery or suffering caused by bad luck or destiny.\nExample (BN): 'অদৃষ্টের কিল খেয়ে তার জীবন সর্বস্ব হারিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 44", topic: "Page 44", q: "অদৃষ্টের পরিহাস/ফের", a: "ভাগ্যবিড়ম্বনা/ভাগ্যের নিষ্ঠুরতা\nEnglish: Cruel twist of fate / destiny's mockery.\nExplanation: When fate or chance plays a cruel or ironic trick on someone.\nExample (BN): 'অদৃষ্টের পরিহাস এমনভাবে তাকে যন্ত্রণা দিয়েছে।'" }
    
   
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অধঃপাতে যাওয়া", a: "উচ্ছন্নে যাওয়া/ধ্বংস হওয়া\nEnglish: To be destroyed / to be ruined.\nExplanation: Complete ruin or destruction of something or someone.\nExample (BN): 'অনৈতিক কাজের কারণে তার ব্যবসা অধঃপাতে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অনধিকারচর্চা", a: "সীমার বাইরে পদক্ষেপ\nEnglish: Exceeding one's authority / overstepping boundaries.\nExplanation: Taking action beyond one's rights or jurisdiction.\nExample (BN): 'এটি অনধিকারচর্চা, তুমি এমন সিদ্ধান্ত নিতে পারো না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অনলে জল পড়া", a: "কঠিন রাগ কমে যাওয়া\nEnglish: Cooling down / anger subsiding.\nExplanation: When intense anger or rage gradually diminishes.\nExample (BN): 'তার মৃদু কথায় অনলে জল পড়ার মতো রাগ কমে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অনুরোধে ঢেঁকি গেলা", a: "অনুরোধে কাজ সম্পন্ন করতে ইচ্ছুক\nEnglish: Willing to help upon request / complying with request.\nExplanation: Being ready to do something when asked, even if difficult.\nExample (BN): 'তিনি অনুরোধে ঢেঁকি গেলার মতো সাহায্য করেছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অনেক কাঠখড় পোড়ানো", a: "বহু চেষ্টা ও পরিশ্রম করা\nEnglish: To go through great effort / to work hard.\nExplanation: Spending a lot of time, energy, and resources to accomplish something.\nExample (BN): 'এই স্বপ্ন পূরণে আমাকে অনেক কাঠখড় পোড়াতে হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্তঃসারশূন্য", a: "গুণহীন ব্যক্তি\nEnglish: Hollow / lacking inner worth.\nExplanation: Someone who appears good on the surface but lacks any real virtue or substance.\nExample (BN): 'তার অন্তঃসারশূন্য ব্যক্তিত্ব দ্রুত স্পষ্ট হয়ে উঠল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্তর টিপুনি", a: "গোপন ব্যথা\nEnglish: Hidden pain / suppressed grief.\nExplanation: Internal suffering that one keeps hidden from others.\nExample (BN): 'তার মুখে হাসি থাকলেও অন্তর টিপুনি তাকে কাঁদায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধকার দেখা", a: "বিপদে দিশেহারা হয়ে পড়া\nEnglish: To see darkness / to become confused in danger.\nExplanation: Losing one's way or sense of direction in a difficult situation.\nExample (BN): 'বিস্ফোরণে সবাই অন্ধকার দেখে যন্ত্রণা ক্রন্দন করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধকারে ঢিল ছোঁড়া/মারা", a: "অনুমানে/আন্দাজে কাজ করা\nEnglish: Shooting in the dark / guessing blindly.\nExplanation: Acting without proper information or taking a wild guess.\nExample (BN): 'সঠিক তথ্য ছাড়া অন্ধকারে ঢিল মারা ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধকারে থাকা", a: "কিছু না জানা/সম্পূর্ণ অজানা/থই না পাওয়া\nEnglish: To be in the dark / to be completely unaware.\nExplanation: Not knowing anything about a situation or being kept uninformed.\nExample (BN): 'এই ব্যাপারে সম্পূর্ণ অন্ধকারে থাকলাম আমরা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধকারে হাতড়ানো", a: "অনুমান করা\nEnglish: To grope in the dark / to guess.\nExplanation: Trying to find one's way without clear knowledge or information.\nExample (BN): 'সমাধান খুঁজতে গিয়ে তিনি অন্ধকারে হাতড়াচ্ছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধের যটি/ষষ্ঠি/নড়ি", a: "অসহায়ের একমাত্র অবলম্বন\nEnglish: A blind man's staff / only support.\nExplanation: The only thing or person that a helpless person can rely upon.\nExample (BN): 'দারিদ্র্যের মধ্যে তার সন্তান অন্ধের যটির মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধের হস্তীদর্শন", a: "অসম্পূর্ণ বিচার/সিদ্ধান্ত\nEnglish: Partial judgment / incomplete understanding.\nExplanation: Making a judgment based on incomplete information, like a blind man touching parts of an elephant.\nExample (BN): 'আধেক তথ্যে আধেক বিচার হয় যা অন্ধের হস্তীদর্শন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধবিশ্বাস", a: "নির্বিচার আস্থা\nEnglish: Blind faith / unconditional belief.\nExplanation: Believing something without any critical thinking or evidence.\nExample (BN): 'অন্ধবিশ্বাস করা বিজ্ঞানের সাথে সামঞ্জস্যপূর্ণ নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ধিসন্ধি", a: "কুমতলব/ষড়যন্ত্র\nEnglish: Conspiracy / scheming.\nExplanation: Secret plotting or machination against someone.\nExample (BN): 'তার সাফল্যে ঈর্ষান্বিত হয়ে অনেকে অন্ধিসন্ধি করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্নকষ্ট", a: "খাদ্যাভাব\nEnglish: Food scarcity / famine.\nExplanation: Lack of sufficient food or sustenance.\nExample (BN): 'অন্নকষ্টে ভুগে সেই পরিবার দান খোঁজে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্নজল", a: "জীবিকা\nEnglish: Livelihood / means of subsistence.\nExplanation: The basic necessities of life (food and water) or the way one earns for living.\nExample (BN): 'সততার সাথে অন্নজল অর্জন করাই প্রকৃত সম্পদ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্ন ধ্বংস করা", a: "বসে বসে খাওয়া\nEnglish: To live without labor / to eat without working.\nExplanation: Enjoying the benefits of life without putting in any effort.\nExample (BN): 'বসে বসে খাওয়ার মানসিকতা সমাজের ক্ষতি করে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অন্নের সংস্থান", a: "জীবিকার উপায়\nEnglish: Means of livelihood / source of food.\nExplanation: The way or method by which one earns or obtains food.\nExample (BN): 'শিক্ষা পেলে অন্নের সংস্থান সহজ হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অপাঙ্গে দেখা", a: "আড়াচোখে দেখা\nEnglish: Sidelong glance / look askance.\nExplanation: Looking at someone with suspicion or disdain through the corner of one's eye.\nExample (BN): 'তার অপাঙ্গে দেখার অর্থ বুঝতে পেরে আমি বিরক্ত হয়েছি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অপোগণ্ড", a: "অপদার্থ/কোন কাজের নয়\nEnglish: Useless / good-for-nothing.\nExplanation: Someone or something that is of no value or utility.\nExample (BN): 'এই অপোগণ্ড যন্ত্রটি ফেলে দেওয়া উচিত।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অবরে-সবরে", a: "কখনো সখনো/কালেভদ্রে\nEnglish: Now and then / occasionally / rarely.\nExplanation: Something that happens infrequently or at irregular intervals.\nExample (BN): 'তিনি অবরে-সবরে শহরে গিয়ে দেখা করেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অবস্থা বুঝে ব্যবস্থা", a: "পরিস্থিতি বিবেচনায় কার্যক্রম গ্রহণ\nEnglish: To adapt one's action to circumstance.\nExplanation: Making decisions that are appropriate and suitable to the current situation.\nExample (BN): 'বুদ্ধিমান ব্যক্তি অবস্থা বুঝে ব্যবস্থা নিয়ে থাকে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অবোধের খাটনি ভারি", a: "বোকাকে বেশি খাটানো যায়\nEnglish: The fool works hard / foolish people work the most.\nExplanation: Simple-minded people can be easily put to work and exploited.\nExample (BN): 'অবোধের খাটনি ভারি বলে তাকে সবচেয়ে বেশি কাজ দেওয়া হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অভাবে স্বভাব নষ্ট", a: "অর্থাভাবে সৎপথ থেকে বিচ্যুতি\nEnglish: Poverty corrupts character / need makes one dishonest.\nExplanation: When someone becomes dishonest or immoral due to lack of resources.\nExample (BN): 'অভাবে স্বভাব নষ্ট হয়ে তিনি চুরি করতে শুরু করেছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অমনি অমনি", a: "কারণ ছাড়া\nEnglish: Without reason / for no cause.\nExplanation: Something happening or being said without any particular reason.\nExample (BN): 'কোন কারণ ছাড়াই অমনি অমনি তিনি রেগে গেলেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অমাবস্যার চাঁদ", a: "দুর্লভ বস্তু/যার দেখা পাওয়া যায় না\nEnglish: A new moon / something extremely rare or never seen.\nExplanation: Something that is virtually impossible to find or see.\nExample (BN): 'এমন সৎ ব্যক্তি অমাবস্যার চাঁদের মতো বিরল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অমৃতে অরুচি", a: "অতি প্রিয় বিষয়ের প্রতি অনীহা\nEnglish: Indifference to the best things / disgust with nectar.\nExplanation: Losing interest in something one loves, or becoming apathetic.\nExample (BN): 'বার বার হতাশায় তার সংগীতপ্রেমে অমৃতে অরুচি দেখা দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অরণ্যে রোদন", a: "নিষ্ফল আবেদন\nEnglish: Crying in the wilderness / fruitless appeal.\nExplanation: Making an appeal or request that goes unheeded or has no effect.\nExample (BN): 'তার ন্যায়ের দাবি অরণ্যে রোদনের মতো ব্যর্থ হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অর্জুনের গাণ্ডীব", a: "দুষ্ট দমনকারী\nEnglish: Destroyer of evil / one who punishes the wicked.\nExplanation: A powerful force or person capable of eliminating wrongdoing.\nExample (BN): 'তিনি অর্জুনের গাণ্ডীবের মতো অন্যায় দূর করেছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অর্থদণ্ড/নাশ", a: "অকারণে অর্থব্যয়\nEnglish: Wasteful spending / unnecessary expense.\nExplanation: Spending money foolishly without any valid reason.\nExample (BN): 'তার এই অর্থদণ্ড দেখে পরিবার হতাশ হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অর্ধচন্দ্র দেওয়া", a: "গলাধাক্কা দেওয়া\nEnglish: To choke / to grab by the throat.\nExplanation: Strangling someone or giving them a choking grip.\nExample (BN): 'ঝগড়ায় তিনি তার প্রতিদ্বন্দ্বীকে অর্ধচন্দ্র দিয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অশনিসঙ্কেত", a: "ঘোর বিপদের সম্ভাবনা\nEnglish: Sign of impending doom / warning of danger.\nExplanation: An indication or warning that great danger is approaching.\nExample (BN): 'অশনিসঙ্কেত দেখে সমাজ প্রস্তুত হতে শুরু করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অষ্টকপালে", a: "অভাগা\nEnglish: Unfortunate / ill-fated.\nExplanation: Someone who is cursed with bad luck from birth.\nExample (BN): 'অষ্টকপালে হিসেবে তার জীবন দুর্ভোগে পূর্ণ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অষ্টপ্রহর", a: "সারা দিনরাত\nEnglish: Day and night / all the time / constantly.\nExplanation: Throughout the entire twenty-four hours or continuously.\nExample (BN): 'অষ্টপ্রহর পরিশ্রম করে তিনি সফল হয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অসার কথা", a: "অর্থহীন/আজেবাজে কথাবার্তা\nEnglish: Nonsense / meaningless talk.\nExplanation: Speech or statements that have no substance or real meaning.\nExample (BN): 'তার অসার কথা শুনে সবাই উপেক্ষা করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অহরহ", a: "প্রতিনিয়ত\nEnglish: Constantly / continuously / day after day.\nExplanation: Something that happens repeatedly or without stopping.\nExample (BN): 'অহরহ বৃষ্টি হচ্ছে এই অঞ্চলে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অহি-নকুল সম্পর্ক", a: "ভীষণ শত্রুতা\nEnglish: Enmity like that of a snake and mongoose / bitter rivalry.\nExplanation: A relationship of extreme hostility and opposition.\nExample (BN): 'তাদের অহি-নকুল সম্পর্ক সবাই জানে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "অহিতে বিপরীত", a: "মন্দ থেকে ভালো\nEnglish: To turn harm into good / to reverse bad fortune.\nExplanation: Transforming a negative situation into a positive one.\nExample (BN): 'তার বুদ্ধিমত্তা অহিতে বিপরীত করে দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "আঁকুপাঁকু", a: "অত্যন্ত ব্যাকুলতা/ছটফট করা\nEnglish: Extreme restlessness / agitation.\nExplanation: Being very anxious or agitated, unable to stay calm.\nExample (BN): 'পরীক্ষার আগে সে আঁকুপাঁকু করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "আঁটকপালে", a: "হতভাগ্য\nEnglish: Unlucky / unfortunate.\nExplanation: Describes someone who suffers from misfortune.\nExample (BN): 'সেই পরিবারটি খুব আঁটকুড়ে; সবসময় সমস্যা পায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "আঁটকুড়ে", a: "নিঃসন্তান\nEnglish: Childless / barren.\nExplanation: Refers to couples who have no children.\nExample (BN): 'তারা দীর্ঘদিন বিবাহিত কিন্তু আঁটকপালে রয়েছেন।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 45", topic: "Page 45", q: "আঁতে ঘা দেওয়া", a: "অন্তরে কষ্ট দেওয়া/প্রকাশ্যে অপমান করা\nEnglish: To wound someone emotionally / to publicly humiliate.\nExplanation: Causing deep emotional pain or insulting someone openly.\nExample (BN): 'তার তিক্ত মন্তব্য সবাইকে আঁতে ঘা দিয়েছে।'" }
    
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আঁতের টান", a: "নাড়ীর/প্রাণের টান (আবেগী আকর্ষণ)\nEnglish: Emotional/innate attachment.\nExplanation: A deep, instinctive pull or longing toward someone or something.\nExample (BN): 'দেশের মাটির প্রতি আঁতের টান তাকে ফিরিয়ে এনেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আঁধার ঘরের প্রদীপ/আঁধার মানিক", a: "দুঃখীর ঘরে একমাত্র সুখের বস্তু/প্রাণাধিক সন্তান\nEnglish: The only light/treasure in a poor person's home.\nExplanation: Refers to a beloved child who is the sole comfort in a poor household.\nExample (BN): 'স্বামী-মায়ের জন্য সেই ছেলে আঁধার ঘরের প্রদীপ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আঁধারে ঢিল ছোঁড়া", a: "আন্দাজে কিছু বলা/করা\nEnglish: To say or do something by guesswork / to speculate.\nExplanation: Acting or commenting without certainty, relying on conjecture.\nExample (BN): 'তথ্য না জেনে আঁধারে ঢিল ছোঁড়া ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আঁস্তাকুড়ের পাত/পাতা", a: "হেয় ব্যক্তি\nEnglish: A contemptible / despicable person.\nExplanation: Someone considered lowly or unworthy of respect.\nExample (BN): 'বেশি মিথ্যাচার করে সে আঁস্তাকুড়ের পাত সহ অন্যান্যদের অসম্মান পায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আউলা-ঝাউলা", a: "অপরিচ্ছন্ন/আলুথালু/এলোমেলো\nEnglish: Unkempt / messy / shabby.\nExplanation: Describes clothing or appearance that is untidy and disorderly.\nExample (BN): 'বহুদিন না গোছানোর ফলে তার পোশাক আউলা-ঝাউলা হয়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাট মূর্খ", a: "জড়বুদ্ধিসম্পন্ন/নিরেট বোকা\nEnglish: Stupid / blockheaded.\nExplanation: A person lacking common sense or quick understanding.\nExample (BN): 'এমন ভুল করবে এমন আচরণ দেখে তাকে আকাট মূর্খ বলা হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকার-ইঙ্গিতে", a: "চোখ ও মুখের ভঙ্গীতে\nEnglish: By gestures / through looks and expressions.\nExplanation: Communicating silently using facial expressions or gestures.\nExample (BN): 'তারা আলোচনা না করে আকৃতি-ইঙ্গিতে বোঝে নেয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশ থেকে পড়া", a: "না জানার ভান করা\nEnglish: To pretend ignorance / to play dumb.\nExplanation: Acting as if one does not know or understand something.\nExample (BN): 'প্রশ্ন এলে সে আকাশ থেকে পড়ার ভান করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশ ভেঙে পড়া (মাথায়)", a: "হঠাৎ ভীষণ বিপদে দিশেহারা হওয়া\nEnglish: To be suddenly overwhelmed by disaster.\nExplanation: Experiencing sudden catastrophic trouble that leaves one helpless.\nExample (BN): 'ব্যবসায় নষ্ট হলে তার জীবন আকাশ ভেঙে পড়ার মতো হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশকুসুম", a: "অসম্ভব\nEnglish: Fantastical / impossible.\nExplanation: Something fanciful or unreal, not likely to happen.\nExample (BN): 'তার পরিকল্পনা আকাশকুসুম; বাস্তবে সম্ভব নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশচুম্বি/ছোঁয়া", a: "অতি উচ্চ\nEnglish: Sky-high / extremely lofty.\nExplanation: Reaching very great heights in achievement, price, or stature.\nExample (BN): 'তার সফলতা আকাশচুম্বি; সবাই দারুণভাবে প্রশংসা করে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশপাতাল চিন্তা/ভাবনা", a: "উদ্দেশ্যহীন নানা প্রকার দুশ্চিন্তা\nEnglish: Frivolous or aimless worries.\nExplanation: Worries and thoughts that are exaggerated or without purpose.\nExample (BN): 'বহু সময় আকাশপাতাল চিন্তায় কাটে তার, তবে কোনো ফল হয় না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশে তোলা", a: "প্রশংসায় পঞ্চমুখ\nEnglish: To praise lavishly / to exalt.\nExplanation: Showering someone or something with high praise.\nExample (BN): 'সংসদে তার কাজ আকাশে তোলা হলো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশে থুথু ফেলা", a: "নিজের ক্ষতি করা\nEnglish: To spit at the sky / to harm oneself.\nExplanation: Acting in a way that ultimately causes self-harm or embarrassment.\nExample (BN): 'অলোচনার মধ্যে নিজের বিরুদ্ধে বাক্যবল রাখলে তা আকাশে থুথু ফেলার সমান।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকাশের চাঁদ হাতে পাওয়া", a: "দুর্লভ বস্তু প্রাপ্তি\nEnglish: To obtain the moon from the sky / to achieve something rare.\nExplanation: Acquiring something very rare or nearly impossible.\nExample (BN): 'এই পুরস্কার পেয়ে যেন আকাশের চাঁদ হাতে পেলাম।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আকুলি-বিকুলি", a: "অতিশয় ব্যাকুলতা\nEnglish: Extreme eagerness / frantic anxiety.\nExplanation: Being excessively restless or anxious about something.\nExample (BN): 'বিলাপ শুনে সবাই আকুলি-বিকুলি হয়ে উঠল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আক্কেল গুড়ুম", a: "হতবুদ্ধি/স্তম্ভিত\nEnglish: Stupefied / bewildered.\nExplanation: Being so surprised or shocked that one becomes speechless.\nExample (BN): 'অফারের খবর পেয়ে সে আক্কেল গুড়ুম হয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আক্কেলদাঁত না গজানো", a: "অপরিণত বুদ্ধির পরিচয় দেওয়া\nEnglish: Showing immaturity / lack of wisdom.\nExplanation: Acting in a childish or immature way that reveals poor judgment.\nExample (BN): 'এমন সিদ্ধান্তে সে আক্কেলদাঁত না গজানোর প্রমাণ দিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আক্কেল সেলামী", a: "নির্বুদ্ধিতার দণ্ড/ভুলের মাশুল\nEnglish: Penalty for foolishness / consequence of error.\nExplanation: The adverse result one suffers for being foolish.\nExample (BN): 'তার অবহেলার কারণে এখন আক্কেল সেলামী ভোগ করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আখের গুছানো", a: "ভবিষ্যৎ গুছিয়ে নেওয়া\nEnglish: To secure the future / to arrange provision.\nExplanation: Making plans or provisions for future stability.\nExample (BN): 'বাচ্চাদের পড়াশোনা নিয়ে আখের গুছিয়েছে তারা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আখেরি জমানা", a: "শেষযুগ/কলিযুগ\nEnglish: The end times / final era.\nExplanation: Referring metaphorically to a distant final period or decline.\nExample (BN): 'বড়লোকের আচরণ দেখে মনে হয় আখেরি জমানা এসে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আগড়ম বাগড়ম", a: "অপ্রাসঙ্গিক/অর্থহীন কথাবার্তা\nEnglish: Irrelevant chatter / nonsense.\nExplanation: Talk that has no relevance or substance.\nExample (BN): 'তার আগড়ম বাগড়ম থামাও, কাজে লাগবে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আগুন ধরানো/লাগানো", a: "তীব্র বিরোধ সৃষ্টি করা\nEnglish: To set fire / to incite intense conflict.\nExplanation: Provoking or initiating a serious dispute or fight.\nExample (BN): 'রাজনৈতিক উসকানিতে কেউ আগুন ধরাচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আগুন নিয়ে খেলা", a: "বিপজ্জনক বিষয় নিয়ে নাড়াচাড়া করা\nEnglish: Playing with fire / dabbling in danger.\nExplanation: Engaging in risky or dangerous behavior that may have severe consequences.\nExample (BN): 'অনভিজ্ঞ দ্বারা এই প্রকল্পে আগুন নিয়ে খেলা হচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আগুন লাগা সংসার", a: "নষ্ট হচ্ছে এমন সংসার\nEnglish: A family falling apart / household in ruin.\nExplanation: Describes a household undergoing severe trouble or breakdown.\nExample (BN): 'অর্থ নিয়ে তর্ক-আপসায় তাদের আগুন লাগা সংসার হয়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আগুনে ঘি ঢালা", a: "রাগ বাড়ানো\nEnglish: To add fuel to the fire / to increase anger.\nExplanation: Doing something that worsens an already tense situation.\nExample (BN): 'অতিরিক্ত মন্তব্য করে সে আলোচনায় আগুনে ঘি ঢালল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আঙ্গুল ফুলে কলাগাছ", a: "হঠাৎ প্রচুর ধনসম্পত্তির মালিক\nEnglish: To suddenly become very wealthy.\nExplanation: Gaining sudden and unexpected wealth or fortune.\nExample (BN): 'ব্যবসায় এক সফল ডিল, আর তিনি আঙ্গুল ফুলে কলাগাছ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আজগুবী কথা", a: "আজেবাজে/অপ্রাসঙ্গিক কথা\nEnglish: Absurd / nonsensical talk.\nExplanation: Saying strange or irrelevant things that make no sense.\nExample (BN): 'তার আজগুবী কথা সবাই বাজে মনে করে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আটপৌরে", a: "সবসময়ের পোশাক\nEnglish: Everyday wear / habitual clothing.\nExplanation: Clothing one habitually wears or always keeps.\nExample (BN): 'সে সাধারণত সাদা কুর্তা পড়েন, সেটাই তার আটপৌরে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আঠারো মাসে বছর", a: "দীর্ঘ সময়\nEnglish: A very long time / seemingly endless.\nExplanation: An idiom meaning a period that feels much longer than usual.\nExample (BN): 'প্রতীক্ষায় দিনগুলি আঠারো মাসে বছর মনে হচ্ছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আড়িপাতা", a: "আড়াল থেকে লুকিয়ে কথা শোনা\nEnglish: Eavesdropping / spying.\nExplanation: Observing or listening secretly to others' conversations.\nExample (BN): 'সে দরজার আড়িপাতা দিয়ে কথোপকথন শুনছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আদা জল খেয়ে পড়ে থাকা", a: "কার্যসিদ্ধির জন্য ধর্ণা দেওয়া\nEnglish: To stage a sit-in / to fast or protest for success.\nExplanation: Taking a persistent stand (often physically) to achieve a purpose.\nExample (BN): 'তারা অনুমতির জন্য আদা জল খেয়ে পড়ে আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আদা জল খেয়ে লাগা", a: "প্রাণপণ চেষ্টা করা\nEnglish: To strive desperately / to make a last-ditch effort.\nExplanation: Putting in extreme effort to accomplish something.\nExample (BN): 'প্রকল্প শেষ করতে তারা আদা জল খেয়ে লাগল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আদায় কাঁচকলায়", a: "তিক্ত সম্পর্ক/চিরশত্রুতা\nEnglish: Bitter enmity / perpetual hostility.\nExplanation: Longstanding and unforgiving hostility between parties.\nExample (BN): 'দুই পরিবারের মধ্যে আদায় কাঁচকলায় চলে এসেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আদার ব্যাপারী", a: "নগণ্য/সামান্য ব্যক্তি\nEnglish: A petty person / insignificant trader.\nExplanation: Someone of little importance or influence.\nExample (BN): 'সব ব্যাপারে হিংসুক-সামান্য মানুষকে আদার ব্যাপারী বলা হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আদ্যোপান্ত", a: "শুরু থেকে শেষ\nEnglish: From beginning to end / thoroughly.\nExplanation: Covering something completely from start to finish.\nExample (BN): 'আদ্যোপান্ত প্রতিবেদনটি পড়ে টেবিলে বসেছি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আপন কোলে ঝোল টানা", a: "নিজের স্বার্থ দেখা\nEnglish: To mind one's own interest / look after one's own benefit.\nExplanation: Acting primarily to serve one's personal advantage.\nExample (BN): 'তিনি সবসময় আপন কোলে ঝোল টানেন, অন্যদের চিন্তা করেন না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আপন পায়ে কুড়াল মারা", a: "নিজের ক্ষতি করা\nEnglish: To bring harm upon oneself / to shoot oneself in the foot.\nExplanation: Doing something that results in one's own detriment.\nExample (BN): 'অজ্ঞানে কার্যকলে সে আপন পায়ে কুড়াল মারল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আমড়া কাঠের ঢেঁকি", a: "অপদার্থ\nEnglish: Worthless / incompetent.\nExplanation: Someone inept or not fit for useful work.\nExample (BN): 'কাজে তার আমড়া কাঠের ঢেঁকি স্বভাব আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আমতা আমতা করা", a: "অস্পষ্ট স্বীকারোক্তি\nEnglish: Vague confession / hesitant admission.\nExplanation: Making an unclear or half-hearted admission or statement.\nExample (BN): 'সে অপরাধ সম্পর্কে আমতা আমতা করে স্বীকার করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আলাদীনের প্রদীপ", a: "অবিশ্বাস্য ঘটনা ঘটানোর কারিগর\nEnglish: Aladdin's lamp / a source of miraculous help.\nExplanation: Metaphor for something that produces incredible, almost magical results.\nExample (BN): 'নতুন আবিষ্কারটি আলাদীনের প্রদীপের মতো সহায়ক হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আলালের ঘরের দুলাল", a: "অতি আদরে বড়লোকের নষ্টপুত্র\nEnglish: Spoiled son of a wealthy patron.\nExplanation: A child excessively pampered by a rich family, often becoming arrogant.\nExample (BN): 'শহরে সে আলালের ঘরের দুলাল হিসেবে পরিচিত।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 46", topic: "Page 46", q: "আষাঢ়ে গল্প", a: "আজগুবি/কাল্পনিক কাহিনী\nEnglish: Tall tale / fanciful story.\nExplanation: A story that is fanciful, implausible, or made up.\nExample (BN): 'তার আষাঢ়ে গল্পগুলো শুনে সবাই হেসে ফেলে।'" }

    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ইঁচড়ে পাকা", a: "অকালপক্ব/ভেঁপো/ফাজিল\nEnglish: Premature / over-smart.\nExplanation: A person who pretends to be mature or clever without proper experience.\nExample (BN): 'সে ইঁচড়ে পাকা ছেলে, বয়সের তুলনায় বেশি চালাক।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ইঁদুর কপালে", a: "নিতান্ত মন্দ ভাগ্য\nEnglish: Extreme bad luck.\nExplanation: Used to describe someone who is very unfortunate.\nExample (BN): 'এমন সুযোগ না পাওয়া একেবারে ইঁদুর কপালে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ইতর বিশেষ", a: "পার্থক্য\nEnglish: Difference / distinction.\nExplanation: Indicates a noticeable difference between things or people.\nExample (BN): 'দুজনের মধ্যে ইতর বিশেষ কিছু নেই।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ইন্ধন জোগানো", a: "উত্তেজনা বৃদ্ধি করা\nEnglish: To fuel something.\nExplanation: To increase intensity or excitement, often negatively.\nExample (BN): 'তার কথাবার্তা ঝগড়ায় ইন্ধন জোগাল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ইলশে গুঁড়ি", a: "গুড়ি গুড়ি বৃষ্টি\nEnglish: Drizzle.\nExplanation: Light rain falling continuously.\nExample (BN): 'সকাল থেকে ইলশে গুঁড়ি বৃষ্টি হচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ইস্পার কি উম্পার", a: "চরম নিস্পত্তি\nEnglish: Final settlement.\nExplanation: A situation that has reached a definite conclusion.\nExample (BN): 'আজ এই মামলার ইস্পার কি উম্পার হবে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঈদের চাঁদ", a: "আকাঙ্ক্ষিত বস্তু\nEnglish: Rare sight.\nExplanation: Something that is rarely seen or eagerly awaited.\nExample (BN): 'ওকে দেখা যায় ঈদের চাঁদের মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঈশানের মেঘ", a: "সঙ্কটের পূর্বভাস\nEnglish: Sign of danger.\nExplanation: An indication of upcoming trouble.\nExample (BN): 'তার আচরণে ঈশানের মেঘ দেখা যাচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঈশ্বরপ্রাপ্তি", a: "মৃত্যু\nEnglish: Death.\nExplanation: A respectful term used to refer to someone’s death.\nExample (BN): 'দীর্ঘ রোগভোগের পর তাঁর ঈশ্বরপ্রাপ্তি হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উঁচু গাছে মই বাঁধা", a: "বেশি লাভের প্রত্যাশী\nEnglish: To aim too high.\nExplanation: Expecting excessive profit or success.\nExample (BN): 'অল্প পুঁজিতে উঁচু গাছে মই বাঁধা ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উঁচু ঘর", a: "ভাল বংশ\nEnglish: Noble family.\nExplanation: Refers to someone from a respected lineage.\nExample (BN): 'সে উঁচু ঘরের সন্তান।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উচ্চবাচ্য না করা", a: "ভালোমন্দ কিছু না বলা / নিশ্চুপ থাকা\nEnglish: Remain silent.\nExplanation: Not expressing any opinion.\nExample (BN): 'সে পুরো ঘটনায় উচ্চবাচ্য করল না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উজানে গুণ টানা", a: "নিয়ত বাধা ডিঙিয়ে কাজ করা\nEnglish: To struggle against odds.\nExplanation: Persisting despite continuous obstacles.\nExample (BN): 'সব বাধা পেরিয়ে সে উজানে গুণ টেনে এগিয়ে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উটকো ঝামেলা", a: "বাজে ঝামেলা\nEnglish: Unnecessary trouble.\nExplanation: A problem created without reason.\nExample (BN): 'এই উটকো ঝামেলায় জড়াতে চাই না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উঠতে বসতে", a: "যখন তখন\nEnglish: Constantly.\nExplanation: Something that happens repeatedly.\nExample (BN): 'সে উঠতে বসতে একই কথা বলে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উঠতি বয়স", a: "যৌবনের শুরুতে\nEnglish: Adolescence.\nExplanation: The early stage of youth.\nExample (BN): 'উঠতি বয়সে এমন আচরণ স্বাভাবিক।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উঠে পড়ে লাগা", a: "দৃঢ় সংকল্পে কাজে লাগা\nEnglish: To get down to work seriously.\nExplanation: Starting work with determination.\nExample (BN): 'সে উঠে পড়ে লাগল কাজ শেষ করতে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উড়নচণ্ডী", a: "অমিতব্যয়ী/সম্পত্তি নষ্টকারী\nEnglish: Spendthrift.\nExplanation: Someone who wastes money carelessly.\nExample (BN): 'তার উড়নচণ্ডী স্বভাবেই সব শেষ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উড়ে এসে জুড়ে বসা", a: "হঠাৎ এসে সব নেওয়া\nEnglish: To barge in unexpectedly.\nExplanation: Entering suddenly and taking advantage.\nExample (BN): 'সে উড়ে এসে জুড়ে বসেছে ব্যাপারটায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উড়ো কথা", a: "গুজব/ভিত্তিহীন খবর\nEnglish: Rumour.\nExplanation: Information spread without verification.\nExample (BN): 'উড়ো কথায় কান দেওয়া ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উড়োচিঠি", a: "বেনামী চিঠি\nEnglish: Anonymous letter.\nExplanation: A letter sent without the sender’s identity.\nExample (BN): 'সে একটি উড়োচিঠি পেয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উত্তম মধ্যম দেওয়া", a: "প্রচণ্ড প্রহার / পিটুনি দেওয়া\nEnglish: Severe beating.\nExplanation: To beat someone badly.\nExample (BN): 'চোরটাকে উত্তম মধ্যম দেওয়া হলো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উদোর পিণ্ডি বুধোর ঘাড়ে", a: "একের দোষ অপরের ওপর চালানো\nEnglish: Passing the blame.\nExplanation: Blaming someone else for one’s own fault.\nExample (BN): 'নিজের দোষ উদোর পিণ্ডি বুধোর ঘাড়ে চাপাল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উনপঞ্চাশ বায়ু", a: "পাগলামি\nEnglish: Madness.\nExplanation: Irrational or crazy behaviour.\nExample (BN): 'তার কথাবার্তা উনপঞ্চাশ বায়ু।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উভয়সঙ্কট", a: "দুইদিকেই বিপদ\nEnglish: Dilemma.\nExplanation: A situation with danger on both sides.\nExample (BN): 'এটা তার জন্য উভয়সঙ্কট হয়ে দাঁড়াল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উলুবনে মুক্তা ছড়ানো", a: "অপাত্রে/অস্থানে দামি বস্তু দান\nEnglish: Casting pearls before swine.\nExplanation: Giving something valuable where it is not appreciated.\nExample (BN): 'ওকে উপদেশ দেওয়া উলুবনে মুক্তা ছড়ানো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উসখুস করা", a: "কিছু করার জন্য ব্যস্ত হয়ে পড়া\nEnglish: To become restless.\nExplanation: Becoming eager or impatient to act.\nExample (BN): 'সে কাজের জন্য উসখুস করছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঊনপাঁজুরে", a: "দুর্বল/মন্দভাগ্য\nEnglish: Weak / unfortunate.\nExplanation: Someone physically weak or unlucky.\nExample (BN): 'ঊনপাঁজুরে লোকটার কষ্টের শেষ নেই।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঊনপাঁজুরে", a: "লক্ষ্মীছাড়া/হতভাগা\nEnglish: Ill-fated.\nExplanation: Someone cursed with bad luck.\nExample (BN): 'সে একেবারে ঊনপাঁজুরে লক্ষ্মীছাড়া।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "উনিশ-বিশ", a: "সামান্য পার্থক্য\nEnglish: Slight difference.\nExplanation: Very small difference between things.\nExample (BN): 'দুটোর মধ্যে উনিশ-বিশ ছাড়া কিছু নেই।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঋণচোর", a: "যে কখনও ঋণ শোধ করে না\nEnglish: Debt defaulter.\nExplanation: A person who never repays borrowed money.\nExample (BN): 'ঋণচোর লোকের ওপর ভরসা করা ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "ঋণ-ছ্যাচড়া", a: "যে টাকা থেকেও ঋণ শোধ করে না\nEnglish: Shameless debtor.\nExplanation: Someone who refuses to repay despite having money.\nExample (BN): 'সে একজন ঋণ-ছ্যাচড়া মানুষ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "এক আকাশে দুই সূর্য", a: "প্রবল প্রতিদ্বন্দ্বী\nEnglish: Two rivals cannot coexist.\nExplanation: Two powerful people cannot dominate the same place.\nExample (BN): 'এক প্রতিষ্ঠানে এক আকাশে দুই সূর্য চলে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "এক কথার মানুষ", a: "কথা রাখে এমন ব্যক্তি\nEnglish: Man of his word.\nExplanation: Someone who keeps promises.\nExample (BN): 'সে এক কথার মানুষ, কথা ভাঙে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "এক ক্ষুরে মাথা কামানো", a: "সমপ্রকৃতির\nEnglish: Of the same kind.\nExplanation: People with similar nature or behaviour.\nExample (BN): 'ওরা এক ক্ষুরে মাথা কামানো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "এক গাল মাছি", a: "মহাবিব্রত\nEnglish: Great nuisance.\nExplanation: Something extremely irritating.\nExample (BN): 'এই কাজটা এক গাল মাছি হয়ে দাঁড়িয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "এক গুরুর শিষ্য", a: "সমান দুষ্ট\nEnglish: Birds of a feather.\nExplanation: People with similar bad traits.\nExample (BN): 'ওরা এক গুরুর শিষ্য।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 47", topic: "Page 47", q: "এক গোয়ালের গরু", a: "এক দলভুক্ত\nEnglish: Same group.\nExplanation: Belonging to the same category or faction.\nExample (BN): 'ওরা সবাই এক গোয়ালের গরু।'" }

    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এক চোখা", a: "পক্ষপাতিত্ব\nEnglish: Biased.\nExplanation: Showing favoritism toward one side.\nExample (BN): 'সে এক চোখা হয়ে বিচার করে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এক ঝাঁকের কৈ", a: "এক দল/শ্রেণিভুক্ত\nEnglish: Of the same kind.\nExplanation: Belonging to the same group or category.\nExample (BN): 'ওরা সবাই এক ঝাঁকের কৈ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এক টানা", a: "অবিরাম\nEnglish: Continuously.\nExplanation: Without any break.\nExample (BN): 'সে এক টানা দুই ঘণ্টা পড়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এক ঢিলে দুই পাখি মারা", a: "এক প্রচেষ্টায় উভয় উদ্দেশ্য সাধন করা\nEnglish: Killing two birds with one stone.\nExplanation: Achieving two results with one action.\nExample (BN): 'এই কাজে এক ঢিলে দুই পাখি মারা হলো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এক মাঘে শীত যায় না", a: "বিপদ একবারই আসে না\nEnglish: One effort is not enough.\nExplanation: A single attempt cannot solve everything.\nExample (BN): 'এক মাঘে শীত যায় না—আরো চেষ্টা দরকার।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "একাই একশ", a: "অসাধারণ দক্ষ শক্তি\nEnglish: As capable as a hundred.\nExplanation: Someone extremely efficient alone.\nExample (BN): 'সে একাই একশ, পুরো কাজটা সামলেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "একাদশে বৃহস্পতি", a: "চরম সৌভাগ্য\nEnglish: Great good luck.\nExplanation: Unexpected extreme fortune.\nExample (BN): 'চাকরিটা পাওয়া তার একাদশে বৃহস্পতি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এখানকার মাটি ওখানে", a: "ধান্ধাবাজী\nEnglish: Trickery.\nExplanation: Manipulating matters dishonestly.\nExample (BN): 'সে এখানকার মাটি ওখানে করে লাভ করে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এলাহিকাণ্ড", a: "বিরাট আয়োজন\nEnglish: Grand affair.\nExplanation: An excessively large arrangement.\nExample (BN): 'বিয়েতে একেবারে এলাহিকাণ্ড হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এলেবেলে", a: "গুরুত্বহীন\nEnglish: Careless.\nExplanation: Lacking seriousness or importance.\nExample (BN): 'এলেবেলে কাজে ভুল হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এলোপাথাড়ি", a: "বিশৃঙ্খল\nEnglish: Haphazard.\nExplanation: Without order or planning.\nExample (BN): 'সে এলোপাথাড়ি কথা বলছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "এসপার ওসপার", a: "চরম নিস্পত্তি/চূড়ান্ত মিমাংসা\nEnglish: Final settlement.\nExplanation: A decisive end.\nExample (BN): 'আজ বিষয়টার এসপার ওসপার হবে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওকালতি করা", a: "পক্ষ সমর্থন\nEnglish: To advocate.\nExplanation: Supporting one side.\nExample (BN): 'সে বন্ধুর হয়ে ওকালতি করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওজন বুঝে চলা", a: "আত্মসম্মান বজায় রাখা\nEnglish: Act wisely.\nExplanation: Behaving according to one’s position.\nExample (BN): 'ওজন বুঝে চলা উচিত।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওঁত পাতা", a: "সুযোগের অপেক্ষায় থাকা\nEnglish: To lie in wait.\nExplanation: Waiting for an opportunity.\nExample (BN): 'চোর ওঁত পেতে ছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওয়াকিবহাল", a: "সম্পূর্ণ জ্ঞাত\nEnglish: Well-informed.\nExplanation: Having complete knowledge.\nExample (BN): 'সে বিষয়টা সম্পর্কে ওয়াকিবহাল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওষুধে ধরা", a: "প্রতিক্রিয়া সৃষ্টি হওয়া\nEnglish: To take effect.\nExplanation: Showing reaction or response.\nExample (BN): 'ওষুধে ধরা শুরু হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওষুধ পড়া", a: "যথাযোগ্য প্রভাব পড়া\nEnglish: To be effective.\nExplanation: Proper effect occurring.\nExample (BN): 'এই ওষুধটা ভালোই পড়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ওষ্ঠাগত (প্রাণ)", a: "প্রাণ যায় যায়\nEnglish: At death’s door.\nExplanation: On the verge of death.\nExample (BN): 'রোগীর প্রাণ ওষ্ঠাগত।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "ক অক্ষর গোমাংস", a: "বর্ণপরিচয়হীন\nEnglish: Illiterate.\nExplanation: Unable to read or write.\nExample (BN): 'সে ক অক্ষর গোমাংস।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কইমাছের প্রাণ", a: "সহজে মরে না\nEnglish: Tough survivor.\nExplanation: Extremely resilient.\nExample (BN): 'ও কইমাছের প্রাণ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কখনো কখনো/সখনো", a: "মাঝে মাঝে\nEnglish: Occasionally.\nExplanation: From time to time.\nExample (BN): 'সে কখনো কখনো আসে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কচকচি/কচকচানি/কচকচালি", a: "বাদানুবাদ\nEnglish: Quarrel.\nExplanation: Continuous argument.\nExample (BN): 'তাদের কচকচি লেগেই থাকে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কচুবনে কালাচাঁদ", a: "অপদার্থ ব্যক্তি\nEnglish: Misfit.\nExplanation: Someone useless in context.\nExample (BN): 'সে এখানে কচুবনে কালাচাঁদ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কচ্ছপের কামড়", a: "যা সহজে ছাড়ে না\nEnglish: Hard to get rid of.\nExplanation: Persistent grip or problem.\nExample (BN): 'এই অভ্যাসটা কচ্ছপের কামড়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কড়ায় গণ্ডায়", a: "নিখুঁত হিসাব\nEnglish: Exactly.\nExplanation: Precise calculation.\nExample (BN): 'সে কড়ায় গণ্ডায় হিসাব দিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কড়িতে চতুর কাহনে কানা", a: "কিপ্টে অথচ অপচয়ী\nEnglish: Penny-wise, pound-foolish.\nExplanation: Careful in small matters, wasteful in big ones.\nExample (BN): 'সে কড়িতে চতুর কাহনে কানা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কণ্টকশয্যা", a: "যন্ত্রণাদায়ক অবস্থা\nEnglish: Bed of thorns.\nExplanation: A painful situation.\nExample (BN): 'এই দায়িত্বটা কণ্টকশয্যা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কত ধানে কত চাল", a: "খুব কঠিন অবস্থা\nEnglish: A tough test.\nExplanation: Revealing real difficulty.\nExample (BN): 'এখন বোঝা গেল কত ধানে কত চাল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কথা দিয়ে কথা নেওয়া", a: "কৌশলে তথ্য আদায়\nEnglish: To extract information tactfully.\nExplanation: Getting information through conversation.\nExample (BN): 'সে কথা দিয়ে কথা নিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কথা বেঁচে খাওয়া", a: "কথার বিনিময়ে উপার্জন\nEnglish: Living by talking.\nExplanation: Earning through speech.\nExample (BN): 'সে কথা বেঁচে খায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কথামত চলা", a: "আদেশ মান্য করা\nEnglish: Obey.\nExplanation: Following instructions.\nExample (BN): 'কথামত চলাই ভালো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কথায় চিড়ে ভেজানো", a: "ফাঁকা আশ্বাস\nEnglish: Empty talk.\nExplanation: Promising without action.\nExample (BN): 'ও কথায় চিড়ে ভেজায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কথার নড়চড়", a: "প্রতিশ্রুতিভঙ্গ\nEnglish: Breaking one’s word.\nExplanation: Going back on promises.\nExample (BN): 'তার কথার নড়চড় হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কথার প্যাঁচ/মারপ্যাঁচ", a: "বাকচাতুর্য\nEnglish: Verbal trickery.\nExplanation: Clever use of words.\nExample (BN): 'সে কথার প্যাঁচ জানে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কপাল কাটা", a: "মন্দ ভাগ্য\nEnglish: Ill-fated.\nExplanation: Extremely unlucky.\nExample (BN): 'ওর কপাল কাটা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কপাল গুণে/জোরে", a: "সৌভাগ্যক্রমে\nEnglish: By good luck.\nExplanation: Due to fortune.\nExample (BN): 'কপাল গুণে বেঁচে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কপাল দোষ", a: "মন্দভাগ্য\nEnglish: Bad fate.\nExplanation: Misfortune by destiny.\nExample (BN): 'সবই কপাল দোষ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 48", topic: "Page 48", q: "কপাল ফেরা", a: "সৌভাগ্য লাভ\nEnglish: Change of fortune.\nExplanation: Turning from bad luck to good.\nExample (BN): 'তার কপাল ফেরা শুরু হয়েছে।'" }


    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কম্বলের লোম বাছা", a: "অসাধ্য কাজ/অকাজ করা\nEnglish: An impossible task.\nExplanation: Doing something extremely difficult or impractical.\nExample (BN): 'এই কাজটা কম্বলের লোম বাছার মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "করাতের দাঁত", a: "দুদিকেই বিপদ\nEnglish: Between two dangers.\nExplanation: A situation where both choices are harmful.\nExample (BN): 'সে এখন করাতের দাঁতে পড়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কলকাঠি নাড়া", a: "কুপরামর্শ দেওয়া\nEnglish: To provoke or instigate.\nExplanation: Encouraging trouble or wrongdoing.\nExample (BN): 'পেছন থেকে সে কলকাঠি নাড়ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কলমের খোঁচা", a: "অসৎ আদেশ\nEnglish: Malicious writing.\nExplanation: Harm caused through written words.\nExample (BN): 'কলমের খোঁচায় অনেক ক্ষতি হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কলা দেখানো", a: "ফাঁকি দেওয়া\nEnglish: To deceive.\nExplanation: Avoiding responsibility through tricks.\nExample (BN): 'শেষ মুহূর্তে কলা দেখিয়ে পালাল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কলির সন্ধ্যা", a: "দুর্ভাগ্যের শুরু\nEnglish: Beginning of misfortune.\nExplanation: The start of a bad phase.\nExample (BN): 'ওই দিন থেকেই তার কলির সন্ধ্যা শুরু।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কলুর বলদ", a: "অন্যের ইচ্ছানুসারে একটানা খাটা\nEnglish: One who works blindly.\nExplanation: A person exploited for nonstop labor.\nExample (BN): 'সে অফিসে কলুর বলদ হয়ে আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কষতে কষতে বাঁধন ছেঁড়া", a: "অতি টানাটানির বিপত্তি\nEnglish: Trouble from over-tightening.\nExplanation: Problems caused by excessive pressure.\nExample (BN): 'কষতে কষতে বাঁধন ছেঁড়াই হলো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঁচা বাঁশে ঘুণ ধরা", a: "অল্প বয়সে নষ্ট হওয়ার পথে যাওয়া\nEnglish: Early moral decay.\nExplanation: Corruption at a young age.\nExample (BN): 'ছেলেটার কাঁচা বাঁশে ঘুণ ধরেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঁটা দিয়ে কাঁটা তোলা", a: "শত্রুর বিরুদ্ধে শত্রু লাগিয়ে দমন\nEnglish: Fighting fire with fire.\nExplanation: Solving a problem using similar tactics.\nExample (BN): 'সে কাঁটা দিয়ে কাঁটা তুলল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঁঠালের আমসত্ত্ব", a: "অসম্ভব বস্তু\nEnglish: An impossible thing.\nExplanation: Something unreal or unattainable.\nExample (BN): 'এই আশা কাঁঠালের আমসত্ত্ব।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঁধে কাঁধ মেলানো", a: "পরস্পরে সহযোগিতা করা\nEnglish: To cooperate.\nExplanation: Working together closely.\nExample (BN): 'সবাই কাঁধে কাঁধ মিলিয়ে কাজ করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঁধে ঝুলি নেওয়া", a: "ভিক্ষার জন্য বের হওয়া\nEnglish: To beg.\nExplanation: Seeking alms for survival.\nExample (BN): 'দারিদ্র্যে সে কাঁধে ঝুলি নিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাকভূষণ্ডী", a: "দীর্ঘজীবী ব্যক্তি\nEnglish: A very long-lived person.\nExplanation: Someone who has lived unusually long.\nExample (BN): 'সে গ্রামের কাকভূষণ্ডী।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঞ্চনমূল্য", a: "অগ্নিমূল্য\nEnglish: Extremely costly.\nExplanation: Something priced very high.\nExample (BN): 'এই জমির কাঞ্চনমূল্য।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাটা ঘায়ে নুনের ছিটা", a: "অপমানের উপর অপমান\nEnglish: Adding insult to injury.\nExplanation: Worsening an already painful situation.\nExample (BN): 'তার কথাটা কাটা ঘায়ে নুনের ছিটা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাঠের পুতুল", a: "নির্জীব স্থির\nEnglish: Toy moved by spring; puppet..\nExplanation: Easily controlled by others.\nExample (BN): 'সে কাঠের পুতুল হয়ে বসে ছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কানকাটা", a: "নির্লজ্জ\nEnglish: Shameless.\nExplanation: Lacking shame or modesty.\nExample (BN): 'এত কথা বলেও তার লজ্জা নেই—একেবারে কানকাটা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কান খাড়া করা", a: "মনোযোগী হওয়া\nEnglish: To listen attentively.\nExplanation: Becoming alert and attentive.\nExample (BN): 'খবর শুনে সে কান খাড়া করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কান ভারী করা", a: "কুপরামর্শ দেওয়া\nEnglish: To poison the mind.\nExplanation: Filling someone’s mind with bad advice.\nExample (BN): 'সে বসের কান ভারী করেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কানে আঙুল দেওয়া", a: "না শোনার চেষ্টা করা\nEnglish: To ignore deliberately.\nExplanation: Refusing to listen.\nExample (BN): 'সে সব কথায় কানে আঙুল দেয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কাষ্ঠহাসি", a: "লোক দেখানো আন্তরিকতাহীন হাসি\nEnglish: Forced smile.\nExplanation: A smile without sincerity.\nExample (BN): 'তার হাসিটা ছিল কাষ্ঠহাসি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কুবেরের ধন", a: "বিপুল ধনসম্পদ\nEnglish: Enormous wealth.\nExplanation: Possessing vast riches.\nExample (BN): 'তার কুবেরের ধন আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কুল কাঠের অঙ্গার", a: "তীব্র দহনজ্বালা\nEnglish: Burning pain.\nExplanation: Severe inner suffering.\nExample (BN): 'মনের কুল কাঠের অঙ্গার তাকে পোড়াচ্ছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কুল রাখি কি শ্যাম রাখি", a: "উভয় সংকট\nEnglish: A dilemma.\nExplanation: Difficulty choosing between two options.\nExample (BN): 'এখন কুল রাখি কি শ্যাম রাখি অবস্থা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কূপমণ্ডুক", a: "সীমাবদ্ধ জ্ঞানসম্পন্ন\nEnglish: Narrow-minded person.\nExplanation: Someone with limited outlook.\nExample (BN): 'সে একেবারে কূপমণ্ডুক।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কেঁচো খুঁড়তে সাপ", a: "সামান্য থেকে অসামান্য পরিস্থিতি\nEnglish: Inviting bigger trouble.\nExplanation: A small action causing major problems.\nExample (BN): 'কেঁচো খুঁড়তে সাপ বেরোল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কেউকেটা", a: "গণ্যমান্য সামান্য\nEnglish: Insignificant person.\nExplanation: Someone of little importance.\nExample (BN): 'সে এখানে কেউকেটা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কেতাদুরস্ত", a: "পরিপাটি\nEnglish: Well-dressed.\nExplanation: Neat and well-arranged.\nExample (BN): 'সে খুব কেতাদুরস্ত।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কোণঠাসা করা", a: "বেকায়দায় ফেলা\nEnglish: To corner someone.\nExplanation: Putting someone in a difficult position.\nExample (BN): 'প্রশ্ন করে তাকে কোণঠাসা করা হলো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কোলজোড়া হয়ে থাকা", a: "চিরজীবী হওয়া\nEnglish: To live long.\nExplanation: Remaining alive for a very long time.\nExample (BN): 'সে কোলজোড়া হয়ে থাকুক।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "কোলেপিঠে মানুষ", a: "যত্নে প্রতিপালিত\nEnglish: Pampered.\nExplanation: Raised with excessive care.\nExample (BN): 'সে কোলেপিঠে মানুষ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "ক্ষমতার চিটেগুড়", a: "ক্ষমতার লোভ\nEnglish: Lust for power.\nExplanation: Greed for authority.\nExample (BN): 'তার ক্ষমতার চিটেগুড় আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খইয়ের বন্ধন", a: "উভয়সংকট\nEnglish: A dilemma.\nExplanation: A situation where both choices lead to difficulty.\nExample (BN): 'এখন সে খইয়ের বন্ধনে পড়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খড়কুটো ধরে বাঁচা", a: "শেষ মুহূর্তে তুচ্ছ সাহায্য নেওয়া\nEnglish: Clutching at straws.\nExplanation: Trying any small help when in desperate trouble.\nExample (BN): 'ডুবে যাওয়ার সময় সে খড়কুটো ধরে বাঁচতে চাইল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খণ্ডপ্রলয়", a: "তুমুল কাণ্ড/ঝগড়া, ভীষণ ব্যাপার\nEnglish: Partial catastrophe.\nExplanation: A sudden violent or chaotic situation.\nExample (BN): 'ওই ঘটনায় খণ্ডপ্রলয় বেঁধে গেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খতিয়ে দেখা", a: "বিবেচনা করা\nEnglish: To examine closely.\nExplanation: Inspecting something carefully before deciding.\nExample (BN): 'চুক্তিটা আগে ভালো করে খতিয়ে দেখা দরকার।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খাই খাই করা", a: "সর্বদা খাওয়ার জন্য লালসা প্রকাশ করা\nEnglish: Always craving food.\nExplanation: Showing constant greed for eating.\nExample (BN): 'ছেলেটা সারাদিন খাই খাই করে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খাতাকলমে", a: "সরকারীভাবে\nEnglish: Officially.\nExplanation: Done formally or on record.\nExample (BN): 'খাতাকলমে সিদ্ধান্ত নেওয়া হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খাপ খাওয়ানো", a: "সামঞ্জস্য রক্ষা করে চলা\nEnglish: To adjust.\nExplanation: Adapting to circumstances.\nExample (BN): 'পরিস্থিতির সঙ্গে খাপ খাওয়ানো দরকার।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খাল কেটে কুমির আনা", a: "বিপদ ডেকে আনা\nEnglish: Inviting danger.\nExplanation: Creating trouble knowingly.\nExample (BN): 'এই কাজটা খাল কেটে কুমির আনার মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খিচুড়ি পাকানো", a: "জটিল করা\nEnglish: To complicate matters.\nExplanation: Making a simple issue unnecessarily complex.\nExample (BN): 'সে বিষয়টা খিচুড়ি পাকিয়ে ফেলেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 49", topic: "Page 49", q: "খোদার খাসি", a: "ভাবনামুক্ত ব্যক্তি\nEnglish: Carefree person.\nExplanation: Someone who lives without worry or concern.\nExample (BN): 'সে একেবারে খোদার খাসি।'" }

    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গঙ্গাজলে গঙ্গাপূজা", a: "বিনাব্যয়ে কার্যসিদ্ধি\nEnglish: Accomplishing a task without extra cost.\nExplanation: Doing something using readily available resources without additional expense.\nExample (BN): 'নিজের লোক দিয়েই কাজ সেরে সে গঙ্গাজলে গঙ্গাপূজা করল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গড্ডলিকা প্রবাহ", a: "ভালো-মন্দ বিচার না করে অনুসরণ\nEnglish: Blind imitation.\nExplanation: Following others without thinking whether it is right or wrong.\nExample (BN): 'সে গড্ডলিকা প্রবাহে চলেই ভুল সিদ্ধান্ত নিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গণ্ডারের চামড়া", a: "মান/অপমানবোধ নেই\nEnglish: Thick-skinned.\nExplanation: A person who feels no shame or insult.\nExample (BN): 'অপমান করলেও তার কিছু যায় আসে না, সে গণ্ডারের চামড়া।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গণ্ডায় গণ্ডায়", a: "বহুল পরিমানে\nEnglish: In large numbers.\nExplanation: Something that exists in abundance.\nExample (BN): 'এখানে গণ্ডায় গণ্ডায় লোক জড়ো হয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গতর খাটানো", a: "পরিশ্রম করা\nEnglish: To work very hard.\nExplanation: Doing physical or intense labor.\nExample (BN): 'সফল হতে হলে গতর খাটাতে হয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গভীর জলের মাছ", a: "অনেক বুদ্ধি/ধূর্ত\nEnglish: Very clever person.\nExplanation: Someone who is experienced and tactful.\nExample (BN): 'ওকে ঠকানো সহজ নয়, সে গভীর জলের মাছ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গরিবের ঘোড়ারোগ", a: "অবস্থার অতিরিক্ত চাওয়া\nEnglish: Desire beyond capacity.\nExplanation: Wanting something unaffordable.\nExample (BN): 'দামি ফোন কেনা গরিবের ঘোড়ারোগ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গরু মেরে জুতা দান", a: "বিরাট ক্ষতি করে অল্প ক্ষতিপূরণ\nEnglish: Huge loss with little compensation.\nExplanation: Damage is far greater than what is repaid.\nExample (BN): 'এই ক্ষতিপূরণ গরু মেরে জুতা দানের মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গলা কাটা", a: "বেশি দাম\nEnglish: Overpriced.\nExplanation: Charging an unreasonably high price.\nExample (BN): 'এই দোকানে সবকিছু গলা কাটা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গলায় গলায় পিরীতি", a: "প্রগাঢ় বন্ধুত্ব\nEnglish: Deep friendship.\nExplanation: Very close relationship between people.\nExample (BN): 'তাদের গলায় গলায় পিরীতি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গলায় পা দেওয়া", a: "উৎপীড়ন করা\nEnglish: To oppress.\nExplanation: Harassing or dominating someone.\nExample (BN): 'দুর্বলদের গলায় পা দেওয়া ঠিক নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গলার কাঁটা", a: "কষ্টদায়ক\nEnglish: Painful obstacle.\nExplanation: Something that causes constant trouble.\nExample (BN): 'এই ঋণটা তার গলার কাঁটা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গা এলিয়ে দেওয়া", a: "হাত পা ছেড়ে শুয়ে পড়া\nEnglish: To lie idle.\nExplanation: Giving up effort and resting lazily.\nExample (BN): 'অল্প কাজেই সে গা এলিয়ে দেয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গা ঝাড়া দেওয়া", a: "জড়তা কাটিয়ে কাজে নামা\nEnglish: To shake off laziness.\nExplanation: Becoming active after inactivity.\nExample (BN): 'এবার গা ঝাড়া দিয়ে পড়াশোনা কর।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গা টেপাটেপি করা", a: "ইঙ্গিতে কথা বলা\nEnglish: Communicating indirectly.\nExplanation: Using gestures instead of words.\nExample (BN): 'সে গা টেপাটেপি করে ইঙ্গিত দিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গা-ঢাকা দেওয়া", a: "আত্মগোপন করা\nEnglish: To hide oneself.\nExplanation: Staying hidden to avoid trouble.\nExample (BN): 'পুলিশ এলে সে গা-ঢাকা দিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গুড়ে বালি", a: "আশা করে না পাওয়া\nEnglish: Hopes shattered.\nExplanation: Failure just when success seemed sure.\nExample (BN): 'পরীক্ষার আগে অসুস্থ হয়ে তার গুড়ে বালি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গাঙ্গুরাম তেলি", a: "অতি নগণ্য ব্যক্তি\nEnglish: A person of no importance.\nExplanation: Someone considered insignificant or worthless.\nExample (BN): 'সে নিজেকে বড় ভাবলেও আসলে গাঙ্গুরাম তেলি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গাছে কাঁঠাল গোঁফে তেল", a: "প্রাপ্তির পূর্বেই ভোগের আয়োজন\nEnglish: Counting gains before achievement.\nExplanation: Preparing to enjoy benefits before actually obtaining them.\nExample (BN): 'চাকরি না পেয়েই গাড়ির স্বপ্ন দেখা গাছে কাঁঠাল গোঁফে তেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গাছে তুলে মই কাড়া", a: "আশা দিয়ে আশ্বাস ভঙ্গ করা\nEnglish: Betraying after giving hope.\nExplanation: Leaving someone helpless after raising expectations.\nExample (BN): 'শেষ মুহূর্তে সাহায্য না করে সে গাছে তুলে মই কাড়ল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গাছে না উঠতেই এককাঁদি", a: "কাজে নামার আগেই ফলের প্রত্যাশা\nEnglish: Expecting success too early.\nExplanation: Wanting results before effort.\nExample (BN): 'পরিশ্রম না করেই পুরস্কার চাইলে সেটা গাছে না উঠতেই এককাঁদি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গায়ে ফুঁ দিয়ে বেড়ানো", a: "কোনো দায়িত্ব গ্রহণ না করা\nEnglish: Avoiding responsibility.\nExplanation: Living carelessly without obligations.\nExample (BN): 'সে সারাদিন গায়ে ফুঁ দিয়ে বেড়ায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গায়ের ঝাল ঝাড়া/মেটানো", a: "রাগ দেখানো\nEnglish: Venting anger.\nExplanation: Releasing frustration on others.\nExample (BN): 'বসে বসে কর্মচারীদের উপর গায়ের ঝাল ঝাড়ে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গুরুচণ্ডালী দোষ", a: "লেখায় সাধু ও কথ্য ভাষার একত্র যোগ\nEnglish: Mixing incompatible styles.\nExplanation: Using formal and informal language together incorrectly.\nExample (BN): 'রচনাটিতে গুরুচণ্ডালী দোষ আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোঁফ খেজুরে", a: "নিতান্ত অলস\nEnglish: Extremely lazy.\nExplanation: Someone unwilling to do any work.\nExample (BN): 'সে এত গোঁফ খেজুরে যে কিছুই করে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোঁয়ার গোবিন্দ", a: "নির্বোধ অথচ হঠকারী\nEnglish: Stubborn fool.\nExplanation: A person who is foolish and obstinate.\nExample (BN): 'বোঝালেও সে গোঁয়ার গোবিন্দের মতোই রইল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোকুলের ষাঁড়", a: "ভবঘুরে\nEnglish: Wanderer.\nExplanation: Someone who roams aimlessly.\nExample (BN): 'সে কাজকর্ম না করে গোকুলের ষাঁড়ের মতো ঘুরে বেড়ায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোড়ায় গলদ", a: "শুরুতে ভুল\nEnglish: Flawed from the start.\nExplanation: A mistake made at the beginning causes later failure.\nExample (BN): 'পরিকল্পনাতেই গোড়ায় গলদ ছিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোবর গণেশ", a: "ব্যক্তিত্বহীন ও নির্বোধ\nEnglish: Utterly foolish person.\nExplanation: Someone lacking intelligence and sense.\nExample (BN): 'সে কোনো সিদ্ধান্ত নিতে পারে না, একেবারে গোবর গণেশ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোবরে পদ্মফুল", a: "নিকৃষ্টস্থানে উৎপন্ন উৎকৃষ্ট বস্তু\nEnglish: Excellence in an unlikely place.\nExplanation: Something valuable emerging from a bad situation.\nExample (BN): 'দারিদ্র্যের মাঝেও সে গোবরে পদ্মফুল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গোলক ধাঁধাঁ", a: "জটিল বিষয়/সমস্যা\nEnglish: Complicated puzzle.\nExplanation: A matter that is very confusing.\nExample (BN): 'এই মামলাটা একেবারে গোলক ধাঁধাঁ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গৌরচন্দ্রিকা", a: "ভূমিকা মুখবন্ধ\nEnglish: Introduction.\nExplanation: Preliminary explanation before the main topic.\nExample (BN): 'লেখার আগে অপ্রয়োজনীয় গৌরচন্দ্রিকা দিয়ো না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গৌরী সেনের টাকা", a: "বেহিসাবী অর্থ\nEnglish: Ill-gotten money.\nExplanation: Money spent carelessly without accountability.\nExample (BN): 'সরকারি টাকা গৌরী সেনের টাকা নয়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "গ্রাম নাই তার সীমানা", a: "অন্যায় দাবী বাড়াবাড়ি\nEnglish: Absurd exaggeration.\nExplanation: Making unreasonable claims.\nExample (BN): 'তার দাবি গ্রাম নাই তার সীমানা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "ঘরকুনো", a: "অত্যন্ত গৃহাসক্ত\nEnglish: Homebound person.\nExplanation: Someone who rarely goes outside.\nExample (BN): 'সে একেবারে ঘরকুনো মানুষ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "ঘরপোড়া গরু", a: "কষ্টদায়ক অভিজ্ঞতাসম্পন্ন ব্যক্তি\nEnglish: Burnt by past experience.\nExplanation: Someone cautious due to previous suffering.\nExample (BN): 'ঘরপোড়া গরু সিঁদুরে মেঘ দেখলেই ভয় পায়।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "ঘরে আগুন দেওয়া", a: "সংসারের সুখশান্তি নষ্ট করা\nEnglish: Destroying family peace.\nExplanation: Creating conflict within the household.\nExample (BN): 'তার কথাই ঘরে আগুন দিল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "ঘাটে এসে তরি ডোবা", a: "কাজের শেষ দিকে এসে বিফল হওয়া\nEnglish: Failing at the last moment.\nExplanation: Losing success just before completion.\nExample (BN): 'পরীক্ষায় ভালো করেও শেষে ঘাটে এসে তরি ডুবল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "ঘাড়ে ভূত চাপা", a: "দুষ্টবুদ্ধি মাথায় চাপা\nEnglish: Possessed by bad ideas.\nExplanation: Acting irrationally due to evil intentions.\nExample (BN): 'হঠাৎ এমন কাজ করল যেন ঘাড়ে ভূত চাপা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 50", topic: "Page 50", q: "ঘোড়া ডিঙিয়ে ঘাস খাওয়া", a: "মধ্যবর্তীকে অতিক্রম করা\nEnglish: Skipping proper steps.\nExplanation: Ignoring procedure to reach the goal.\nExample (BN): 'নিয়ম না মেনে সে ঘোড়া ডিঙিয়ে ঘাস খেল।'" }

    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ঘোড়া দেখে খোঁড়া", a: "আরাম পেয়ে আলসেমি করা\nEnglish: Becoming lazy after comfort.\nExplanation: Losing motivation once ease or comfort is achieved.\nExample (BN): 'কাজ পেয়ে সে ঘোড়া দেখে খোঁড়া হয়ে গেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ঘোড়ার ঘাস কাটা", a: "বাজে কাজে সময় নষ্ট\nEnglish: Wasting time on useless work.\nExplanation: Spending effort on meaningless activities.\nExample (BN): 'সে সারাদিন ঘোড়ার ঘাস কাটে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ঘোড়ার ডিম", a: "কিছু না/ফাঁকি\nEnglish: Nothing at all.\nExplanation: Refers to something that does not exist.\nExample (BN): 'ওর কাছ থেকে ঘোড়ার ডিমও পাওয়া যাবে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ঘোড়ারোগ", a: "সাধ্যের অতিরিক্ত বাবুগিরির সাধ\nEnglish: Pretentious lifestyle.\nExplanation: Wanting luxury beyond one’s means.\nExample (BN): 'সাধারণ চাকরিতে ঘোড়ারোগ চলবে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ঘোলা জলে মাছ ধরা", a: "অব্যবস্থার সুযোগে স্বার্থ উদ্ধার\nEnglish: Profiting from chaos.\nExplanation: Taking advantage of disorder.\nExample (BN): 'সে ঝামেলায় ঘোলা জলে মাছ ধরল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চক্ষু চড়কগাছ", a: "আশ্চর্য হওয়া\nEnglish: Being astonished.\nExplanation: Feeling sudden surprise.\nExample (BN): 'খবর শুনে তার চক্ষু চড়কগাছ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চক্ষু ছানাবড়া", a: "অতিশয় বিস্মিত\nEnglish: Extremely surprised.\nExplanation: Being stunned with amazement.\nExample (BN): 'এই দৃশ্য দেখে চক্ষু ছানাবড়া।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চক্ষুলজ্জা", a: "অন্যের সামনে কিছু করতে বা বলতে সংকোচ\nEnglish: Shyness.\nExplanation: Feeling hesitant due to modesty.\nExample (BN): 'তার চক্ষুলজ্জার জন্য কথা বলেনি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চক্ষুশুল", a: "অত্যন্ত অপ্রিয় লোক\nEnglish: Eyesore.\nExplanation: Someone who is very disliked.\nExample (BN): 'সে সবার চক্ষুশুল হয়ে উঠেছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চামচিকের লাথি", a: "নগণ্য ব্যক্তির কটূক্তি/দুর্ব্যবহার\nEnglish: Insignificant insult.\nExplanation: Abuse from a worthless person.\nExample (BN): 'ওর কথা চামচিকের লাথির মতো।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চিনির পুতুল", a: "অল্প শ্রমে কাতর\nEnglish: Overly delicate.\nExplanation: Someone who cannot tolerate hardship.\nExample (BN): 'সে চিনির পুতুল, কষ্ট সহ্য করতে পারে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চিনির বলদ", a: "অপরের সমৃদ্ধির জন্য খেটে মরা ব্যক্তি\nEnglish: Exploited worker.\nExplanation: Someone who works hard for others’ benefit.\nExample (BN): 'সে মালিকের জন্য চিনির বলদ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চুনকালি দেওয়া/লাগা", a: "অপদস্থ হওয়া/লজ্জিত হওয়া\nEnglish: Being disgraced.\nExplanation: Becoming publicly embarrassed.\nExample (BN): 'ভুলের জন্য তার চুনকালি লাগল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চুনোপুঁটি", a: "নগণ্যব্যক্তি\nEnglish: Insignificant person.\nExplanation: Someone with no influence.\nExample (BN): 'সে রাজনীতিতে একেবারে চুনোপুঁটি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোখ কপালে তোলা", a: "বিস্মিত হওয়া\nEnglish: Being amazed.\nExplanation: Showing great surprise.\nExample (BN): 'ফল দেখে চোখ কপালে তুলল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোখে অন্ধকার দেখা", a: "দিশেহারা হয়ে পড়া\nEnglish: Feeling overwhelmed.\nExplanation: Losing sense due to trouble.\nExample (BN): 'খবর পেয়ে তার চোখে অন্ধকার।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোখে আঙ্গুল দিয়ে দেখানো", a: "প্রমাণ দিয়ে বোঝানো\nEnglish: Demonstrating clearly.\nExplanation: Explaining with obvious evidence.\nExample (BN): 'ভুলটা চোখে আঙ্গুল দিয়ে দেখাল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোখে ধূলো দেওয়া", a: "ফাঁকি দেওয়া ঠকানো\nEnglish: Deceiving.\nExplanation: Cheating by trickery.\nExample (BN): 'সে সবার চোখে ধূলো দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোখে সরষে ফুল দেখা", a: "বিপদে দিশেহারা হওয়া\nEnglish: Seeing stars.\nExplanation: Being stunned by trouble.\nExample (BN): 'মাথায় আঘাত পেয়ে চোখে সরষে ফুল দেখল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোখের চামড়া", a: "লজ্জা সংকোচ\nEnglish: Sense of shame.\nExplanation: Feeling embarrassed or modest.\nExample (BN): 'তার চোখের চামড়া নেই।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "চোরের উপর বাটপাড়ি", a: "চোরের কাছ থেকে চোরাই মাল চুরি\nEnglish: Cheating a cheat.\nExplanation: Stealing from a dishonest person.\nExample (BN): 'ওটা চোরের উপর বাটপাড়ি।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছন্দপতন", a: "তালভঙ্গ রসভঙ্গ\nEnglish: Loss of rhythm.\nExplanation: Breaking flow or harmony.\nExample (BN): 'হঠাৎ কথায় ছন্দপতন ঘটল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছল-ছুতো", a: "সামান্য ত্রুটি\nEnglish: Petty excuse.\nExplanation: Minor or false reason.\nExample (BN): 'সে ছল-ছুতো খুঁজছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছাইচাপা আগুন", a: "সুপ্তপ্রতিভা/অব্যক্ত ক্রোধ\nEnglish: Hidden fire.\nExplanation: Suppressed anger or talent.\nExample (BN): 'তার ভিতরে ছাইচাপা আগুন আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছাপোষা অলা বেতনের", a: "অল্প বেতনের কর্মচারী\nEnglish: Low-paid worker.\nExplanation: Someone earning very little.\nExample (BN): 'সে একজন ছাপোষা কর্মচারী।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছেলে-ছোকরা", a: "অল্প বয়স্ক ছেলেরা\nEnglish: Young boys.\nExplanation: Refers to immature youths.\nExample (BN): 'ছেলে-ছোকরা এসব বোঝে না।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছেলেমানুষি", a: "বালকসুলভ আচরণ\nEnglish: Childish behavior.\nExplanation: Acting immaturely.\nExample (BN): 'এটা ছেলেমানুষি কাজ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছেলের হাতের মোয়া", a: "সহজলভ্য বস্তু\nEnglish: Easy to obtain.\nExplanation: Something readily available.\nExample (BN): 'এই কাজ ছেলের হাতের মোয়া।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছোট নজর", a: "কৃপণতা\nEnglish: Stinginess.\nExplanation: Being miserly.\nExample (BN): 'তার ছোট নজর সবার জানা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ছোট মুখে বড় কথা", a: "ছোটদের মুখে বড়দের কথা\nEnglish: Presumptuous speech.\nExplanation: Speaking beyond one’s position.\nExample (BN): 'এটা তোমার ছোট মুখে বড় কথা।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জগদ্দল পাথর", a: "প্রচণ্ড গুরুভার\nEnglish: Heavy burden.\nExplanation: Something extremely difficult to bear.\nExample (BN): 'ঋণ তার জীবনে জগদ্দল পাথর।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জলাঞ্জলি দেওয়া", a: "সম্পূর্ণ পরিত্যাগ করা\nEnglish: Abandon completely.\nExplanation: Giving up entirely.\nExample (BN): 'সে আশা জলাঞ্জলি দিয়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জলে কুমির ডাঙায় বাঘ", a: "উভয় সংকট\nEnglish: Caught between dangers.\nExplanation: Facing danger on both sides.\nExample (BN): 'সে জলে কুমির ডাঙায় বাঘ অবস্থায় পড়েছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জিলাপির প্যাঁচ", a: "অসরল ভাব কুটিলতা\nEnglish: Trickiness.\nExplanation: Complicated or deceptive behavior.\nExample (BN): 'তার কথায় জিলাপির প্যাঁচ আছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জুতা খাওয়া/মারা", a: "অপমানিত হওয়া/আপমান করা\nEnglish: Being insulted.\nExplanation: Facing humiliation.\nExample (BN): 'সে সবার সামনে জুতা খেল।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জেগে স্বপ্ন দেখা", a: "অবাস্তব আশা/কল্পনা করা\nEnglish: Daydreaming.\nExplanation: Imagining unrealistic hopes.\nExample (BN): 'সে জেগে স্বপ্ন দেখে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জোরকদম", a: "দ্রুতগতি\nEnglish: Full speed.\nExplanation: Acting with great force or speed.\nExample (BN): 'কাজটা জোরকদমে চলছে।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জোরজুলুম", a: "উৎপীড়ন / বলপ্রয়োগ\nEnglish: Oppression.\nExplanation: Using force unjustly.\nExample (BN): 'জোরজুলুমে মানুষ অতিষ্ঠ।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "জ্ঞানপাপী", a: "জেনেশুনে যে মিথ্যা কথা বলে\nEnglish: Knowing liar.\nExplanation: Someone who lies deliberately.\nExample (BN): 'সে একেবারে জ্ঞানপাপী।'" }
    ,{ fullSection: "SECTION: Bangla - Idioms - Page 51", topic: "Page 51", q: "ঝড়ঝাপটা", a: "বিপদ আপদ\nEnglish: Turmoil.\nExplanation: Sudden trouble or disaster.\nExample (BN): 'জীবনে অনেক ঝড়ঝাপটা এসেছে।'" }


];


let currentIndex = 0;
let filtered = banglaFlashcards;

function $(id){return document.getElementById(id)}

function display(i){
    if (!filtered || filtered.length===0) return;
    if (i<0) i=0; if (i>=filtered.length) i=filtered.length-1;
    currentIndex=i;
    const c = filtered[i];
    $('sectionText').textContent = c.fullSection;
    $('questionText').textContent = c.q;
    $('answerText').innerText = c.a;
    $('cardCount').textContent = `${i+1} / ${filtered.length}`;
    $('flashcard').classList.remove('flipped');
    const p = ((i+1)/filtered.length)*100; $('progressFill').style.width = p+'%';
}

function next(){ if (currentIndex<filtered.length-1) display(currentIndex+1); }
function prev(){ if (currentIndex>0) display(currentIndex-1); }

function toggle(){ $('flashcard').classList.toggle('flipped'); }

function openModal(){ $('topicModal').style.display='block'; }
function closeModal(){ $('topicModal').style.display='none'; }

function populateTopics(){
    const topics = Array.from(new Set(filtered.map(c=>c.topic)));
    const list = $('topicList'); list.innerHTML='';
    topics.forEach(t=>{
        const div = document.createElement('div'); div.className='topic-item'; div.textContent = `${t} (${filtered.filter(c=>c.topic===t).length} cards)`;
        div.onclick = ()=>{ filtered = banglaFlashcards.filter(c=>c.topic===t); display(0); document.querySelectorAll('.topic-item').forEach(e=>e.classList.remove('active')); div.classList.add('active'); closeModal(); };
        list.appendChild(div);
    });
}

document.addEventListener('DOMContentLoaded', ()=>{
    populateTopics();
    display(0);
    $('flashcard').addEventListener('click', toggle);
    $('nextBtn').addEventListener('click', next);
    $('prevBtn').addEventListener('click', prev);
    $('sectionHeader').addEventListener('click', openModal);
    document.querySelector('.close').addEventListener('click', closeModal);
    document.getElementById('topicModal').addEventListener('click', function(e){ if (e.target===this) closeModal(); });
    document.addEventListener('keydown', function(e){ if (e.key==='ArrowRight') next(); if (e.key==='ArrowLeft') prev(); if (e.key===' ') { e.preventDefault(); toggle(); } });
});

})();
